function log() {
    $.si.debug && window.console && window.console.log && window.console.log("->", arguments)
}
function verifyMobileCode() {
    var n = $.Deferred(), i = $("#Phone").val(), t = $("#ValidateCodeForPhone").val();
    return !i || !t ? (n.reject(), !1) : ($.ajax({
        url: "VerifyMobileCode?{2}&num={0}&code={1}".format($("#Phone").val(), $("#ValidateCodeForPhone").val(), +new Date),
        success: function (t) {
            t.status == "success" ? ($(".product-login").validateErrors([{
                element: $("#ValidateCodeForPhone"),
                msg: t.message.msg
            }], !1), n.resolve()) : ($(".product-login").validateErrors([{
                element: $("#ValidateCodeForPhone"),
                msg: t.message.msg
            }]), n.reject())
        }
    }), n.promise())
}
(function (n) {
    n.si = n.si || {debug: !0}
})(jQuery), function (n) {
    var t = {};
    n.publish = function (i, r) {
        t[i] && n.each(t[i], function () {
            this.apply(n, r || [])
        })
    }, n.subscribe = function (n, i) {
        return t[n] || (t[n] = []), t[n].push(i), [n, i]
    }, n.unsubscribe = function (i) {
        var r = i[0];
        t[r] && n.each(t[r], function (n) {
            this == i[1] && t[r].splice(n, 1)
        })
    }
}(jQuery), String.prototype.format = function (n) {
    var i = this, r, t, u;
    if (arguments.length > 0)if (arguments.length == 1 && typeof n == Object)for (r in n)n[r] != undefined && (u = new RegExp("({" + r + "})", "g"), i = i.replace(u, n[r])); else for (t = 0; t < arguments.length; t++)arguments[t] != undefined && (u = new RegExp("({[" + t + "]})", "g"), i = i.replace(u, arguments[t]));
    return i
}, String.prototype.toJson = function () {
    var t = this.split("&"), u = {}, n, r, i;
    if (t.length > 1)for (n = 0; n < t.length; n++)r = t[n].split("=")[0], i = t[n].split("=")[1], u[r] = i;
    return u
}, String.prototype.getBracketInner = function () {
    var t, u, i, n, r;
    if (!this || this.indexOf("[") == -1)return "";
    for (t = this.split(""), n = 0, r = t.length; n < r; n++)t[n] == "[" ? u = n : t[n] == "]" && (i = n);
    return i ? t.join().replace(/,/g, "").substring(u + 1, i) : ""
}, String.prototype.toLongDate = function () {
    try {
        var n = $.trim(this);
        return $.browser.msie && (n = n.replace(/-/g, "/").replace(/\..+/g, "")), dateFormat(n, "longDateTime")
    } catch (t) {
        window.console && console.log(t)
    }
}, String.prototype.getPureDBC = function () {
    for (var i = "", t, n = 0; n < this.length; n++)code = this.charCodeAt(n), code >= 65281 && code <= 65373 ? (t = this.charCodeAt(n) - 65248, i += String.fromCharCode(t)) : code == 12288 ? (t = this.charCodeAt(n) - 12256, i += String.fromCharCode(t)) : i += this.charAt(n);
    return i
}, String.prototype.getLength = function () {
    for (var t = this.length, n = 0; n < this.length; n++)code = this.charCodeAt(n), (code >= 65281 && code <= 65373 || code == 12288) && (t = t + 1);
    return t
}, Array.prototype.getSameVar = function (n, t) {
    var f = [], i, e, r, u;
    if (n instanceof Array && t instanceof Array)for (i = 0, e = n.length; i < e; i++)for (r = 0, u = t.length; r < u; r++)n[i] === t[r] && f.push(n[i]);
    return f
}, Array.prototype.total = function () {
    for (var t = this, i = 0, n = 0, r = t.length; n < r; n++)typeof t[n] == "number" ? i += t[n] : typeof t[n] == "string" && (i += parseFloat(t[n].replace(/,/g, "")));
    return i
};
var IndexOf = function (n) {
    for (var i = this.length, t = 0; t < i; t++)if (this[t] === n)return t;
    return -1
};
Array.prototype.indexOf = Array.prototype.indexOf || IndexOf, Array.prototype.unequal = function (n) {
    var i = {}, r = this.length, t;
    if (r != 0) {
        for (t = 0; t < r; t++)n && typeof i[this[t][n]] == "undefined" ? i[this[t][n]] = this[t] : n || typeof i[this[t]] != "undefined" || (i[this[t]] = this[t]);
        this.length = 0, r = 0;
        for (t in i)this[r++] = i[t];
        return this
    }
}, String.prototype.makePy = function () {
    function f(n) {
        var i = {
            "19969": "DZ",
            "19975": "WM",
            "19988": "QJ",
            "20048": "YL",
            "20056": "SC",
            "20060": "NM",
            "20094": "QG",
            "20127": "QJ",
            "20167": "QC",
            "20193": "YG",
            "20250": "KH",
            "20256": "ZC",
            "20282": "SC",
            "20285": "QJG",
            "20291": "TD",
            "20314": "YD",
            "20340": "NE",
            "20375": "TD",
            "20389": "YJ",
            "20391": "CZ",
            "20415": "PB",
            "20446": "YS",
            "20447": "SQ",
            "20504": "TC",
            "20608": "KG",
            "20854": "QJ",
            "20857": "ZC",
            "20911": "PF",
            "20504": "TC",
            "20608": "KG",
            "20854": "QJ",
            "20857": "ZC",
            "20911": "PF",
            "20985": "AW",
            "21032": "PB",
            "21048": "XQ",
            "21049": "SC",
            "21089": "YS",
            "21119": "JC",
            "21242": "SB",
            "21273": "SC",
            "21305": "YP",
            "21306": "QO",
            "21330": "ZC",
            "21333": "SDC",
            "21345": "QK",
            "21378": "CA",
            "21397": "SC",
            "21414": "XS",
            "21442": "SC",
            "21477": "JG",
            "21480": "TD",
            "21484": "ZS",
            "21494": "YX",
            "21505": "YX",
            "21512": "HG",
            "21523": "XH",
            "21537": "PB",
            "21542": "PF",
            "21549": "KH",
            "21571": "E",
            "21574": "DA",
            "21588": "TD",
            "21589": "O",
            "21618": "ZC",
            "21621": "KHA",
            "21632": "ZJ",
            "21654": "KG",
            "21679": "LKG",
            "21683": "KH",
            "21710": "A",
            "21719": "YH",
            "21734": "WOE",
            "21769": "A",
            "21780": "WN",
            "21804": "XH",
            "21834": "A",
            "21899": "ZD",
            "21903": "RN",
            "21908": "WO",
            "21939": "ZC",
            "21956": "SA",
            "21964": "YA",
            "21970": "TD",
            "22003": "A",
            "22031": "JG",
            "22040": "XS",
            "22060": "ZC",
            "22066": "ZC",
            "22079": "MH",
            "22129": "XJ",
            "22179": "XA",
            "22237": "NJ",
            "22244": "TD",
            "22280": "JQ",
            "22300": "YH",
            "22313": "XW",
            "22331": "YQ",
            "22343": "YJ",
            "22351": "PH",
            "22395": "DC",
            "22412": "TD",
            "22484": "PB",
            "22500": "PB",
            "22534": "ZD",
            "22549": "DH",
            "22561": "PB",
            "22612": "TD",
            "22771": "KQ",
            "22831": "HB",
            "22841": "JG",
            "22855": "QJ",
            "22865": "XQ",
            "23013": "ML",
            "23081": "WM",
            "23487": "SX",
            "23558": "QJ",
            "23561": "YW",
            "23586": "YW",
            "23614": "YW",
            "23615": "SN",
            "23631": "PB",
            "23646": "ZS",
            "23663": "ZT",
            "23673": "YG",
            "23762": "TD",
            "23769": "ZS",
            "23780": "QJ",
            "23884": "QK",
            "24055": "XH",
            "24113": "DC",
            "24162": "ZC",
            "24191": "GA",
            "24273": "QJ",
            "24324": "NL",
            "24377": "TD",
            "24378": "QJ",
            "24439": "PF",
            "24554": "ZS",
            "24683": "TD",
            "24694": "WE",
            "24733": "LK",
            "24925": "TN",
            "25094": "ZG",
            "25100": "XQ",
            "25103": "XH",
            "25153": "PB",
            "25170": "PB",
            "25179": "KG",
            "25203": "PB",
            "25240": "ZS",
            "25282": "FB",
            "25303": "NA",
            "25324": "KG",
            "25341": "ZY",
            "25373": "WZ",
            "25375": "XJ",
            "25384": "A",
            "25457": "A",
            "25528": "SD",
            "25530": "SC",
            "25552": "TD",
            "25774": "ZC",
            "25874": "ZC",
            "26044": "YW",
            "26080": "WM",
            "26292": "PB",
            "26333": "PB",
            "26355": "ZY",
            "26366": "CZ",
            "26397": "ZC",
            "26399": "QJ",
            "26415": "ZS",
            "26451": "SB",
            "26526": "ZC",
            "26552": "JG",
            "26561": "TD",
            "26588": "JG",
            "26597": "CZ",
            "26629": "ZS",
            "26638": "YL",
            "26646": "XQ",
            "26653": "KG",
            "26657": "XJ",
            "26727": "HG",
            "26894": "ZC",
            "26937": "ZS",
            "26946": "ZC",
            "26999": "KJ",
            "27099": "KJ",
            "27449": "YQ",
            "27481": "XS",
            "27542": "ZS",
            "27663": "ZS",
            "27748": "TS",
            "27784": "SC",
            "27788": "ZD",
            "27795": "TD",
            "27812": "O",
            "27850": "PB",
            "27852": "MB",
            "27895": "SL",
            "27898": "PL",
            "27973": "QJ",
            "27981": "KH",
            "27986": "HX",
            "27994": "XJ",
            "28044": "YC",
            "28065": "WG",
            "28177": "SM",
            "28267": "QJ",
            "28291": "KH",
            "28337": "ZQ",
            "28463": "TL",
            "28548": "DC",
            "28601": "TD",
            "28689": "PB",
            "28805": "JG",
            "28820": "QG",
            "28846": "PB",
            "28952": "TD",
            "28975": "ZC",
            "29100": "A",
            "29325": "QJ",
            "29575": "SL",
            "29602": "FB",
            "30010": "TD",
            "30044": "CX",
            "30058": "PF",
            "30091": "YSP",
            "30111": "YN",
            "30229": "XJ",
            "30427": "SC",
            "30465": "SX",
            "30631": "YQ",
            "30655": "QJ",
            "30684": "QJG",
            "30707": "SD",
            "30729": "XH",
            "30796": "LG",
            "30917": "PB",
            "31074": "NM",
            "31085": "JZ",
            "31109": "SC",
            "31181": "ZC",
            "31192": "MLB",
            "31293": "JQ",
            "31400": "YX",
            "31584": "YJ",
            "31896": "ZN",
            "31909": "ZY",
            "31995": "XJ",
            "32321": "PF",
            "32327": "ZY",
            "32418": "HG",
            "32420": "XQ",
            "32421": "HG",
            "32438": "LG",
            "32473": "GJ",
            "32488": "TD",
            "32521": "QJ",
            "32527": "PB",
            "32562": "ZSQ",
            "32564": "JZ",
            "32735": "ZD",
            "32793": "PB",
            "33071": "PF",
            "33098": "XL",
            "33100": "YA",
            "33152": "PB",
            "33261": "CX",
            "33324": "BP",
            "33333": "TD",
            "33406": "YA",
            "33426": "WM",
            "33432": "PB",
            "33445": "JG",
            "33486": "ZN",
            "33493": "TS",
            "33507": "QJ",
            "33540": "QJ",
            "33544": "ZC",
            "33564": "XQ",
            "33617": "YT",
            "33632": "QJ",
            "33636": "XH",
            "33637": "YX",
            "33694": "WG",
            "33705": "PF",
            "33728": "YW",
            "33882": "SR",
            "34067": "WM",
            "34074": "YW",
            "34121": "QJ",
            "34255": "ZC",
            "34259": "XL",
            "34425": "JH",
            "34430": "XH",
            "34485": "KH",
            "34503": "YS",
            "34532": "HG",
            "34552": "XS",
            "34558": "YE",
            "34593": "ZL",
            "34660": "YQ",
            "34892": "XH",
            "34928": "SC",
            "34999": "QJ",
            "35048": "PB",
            "35059": "SC",
            "35098": "ZC",
            "35203": "TQ",
            "35265": "JX",
            "35299": "JX",
            "35782": "SZ",
            "35828": "YS",
            "35830": "E",
            "35843": "TD",
            "35895": "YG",
            "35977": "MH",
            "36158": "JG",
            "36228": "QJ",
            "36426": "XQ",
            "36466": "DC",
            "36710": "JC",
            "36711": "ZYG",
            "36767": "PB",
            "36866": "SK",
            "36951": "YW",
            "37034": "YX",
            "37063": "XH",
            "37218": "ZC",
            "37325": "ZC",
            "38063": "PB",
            "38079": "TD",
            "38085": "QY",
            "38107": "DC",
            "38116": "TD",
            "38123": "YD",
            "38224": "HG",
            "38241": "XTC",
            "38271": "ZC",
            "38415": "YE",
            "38426": "KH",
            "38461": "YD",
            "38463": "AE",
            "38466": "PB",
            "38477": "XJ",
            "38518": "YT",
            "38551": "WK",
            "38585": "ZC",
            "38704": "XS",
            "38739": "LJ",
            "38761": "GJ",
            "38808": "SQ",
            "39048": "JG",
            "39049": "XJ",
            "39052": "HG",
            "39076": "CZ",
            "39271": "XT",
            "39534": "TD",
            "39552": "TD",
            "39584": "PB",
            "39647": "SB",
            "39730": "LG",
            "39748": "TPB",
            "40109": "ZQ",
            "40479": "ND",
            "40516": "HG",
            "40536": "HG",
            "40583": "QJ",
            "40765": "YQ",
            "40784": "QJ",
            "40840": "YK",
            "40863": "QJG"
        }, r = "YDYQSXMWZSSXJBYMGCCZQPSSQBYCDSCDQLDYLYBSSJGYZZJJFKCCLZDHWDWZJLJPFYYNWJJTMYHZWZHFLZPPQHGSCYYYNJQYXXGJHHSDSJNKKTMOMLCRXYPSNQSECCQZGGLLYJLMYZZSECYKYYHQWJSSGGYXYZYJWWKDJHYCHMYXJTLXJYQBYXZLDWRDJRWYSRLDZJPCBZJJBRCFTLECZSTZFXXZHTRQHYBDLYCZSSYMMRFMYQZPWWJJYFCRWFDFZQPYDDWYXKYJAWJFFXYPSFTZYHHYZYSWCJYXSCLCXXWZZXNBGNNXBXLZSZSBSGPYSYZDHMDZBQBZCWDZZYYTZHBTSYYBZGNTNXQYWQSKBPHHLXGYBFMJEBJHHGQTJCYSXSTKZHLYCKGLYSMZXYALMELDCCXGZYRJXSDLTYZCQKCNNJWHJTZZCQLJSTSTBNXBTYXCEQXGKWJYFLZQLYHYXSPSFXLMPBYSXXXYDJCZYLLLSJXFHJXPJBTFFYABYXBHZZBJYZLWLCZGGBTSSMDTJZXPTHYQTGLJSCQFZKJZJQNLZWLSLHDZBWJNCJZYZSQQYCQYRZCJJWYBRTWPYFTWEXCSKDZCTBZHYZZYYJXZCFFZZMJYXXSDZZOTTBZLQWFCKSZSXFYRLNYJMBDTHJXSQQCCSBXYYTSYFBXDZTGBCNSLCYZZPSAZYZZSCJCSHZQYDXLBPJLLMQXTYDZXSQJTZPXLCGLQTZWJBHCTSYJSFXYEJJTLBGXSXJMYJQQPFZASYJNTYDJXKJCDJSZCBARTDCLYJQMWNQNCLLLKBYBZZSYHQQLTWLCCXTXLLZNTYLNEWYZYXCZXXGRKRMTCNDNJTSYYSSDQDGHSDBJGHRWRQLYBGLXHLGTGXBQJDZPYJSJYJCTMRNYMGRZJCZGJMZMGXMPRYXKJNYMSGMZJYMKMFXMLDTGFBHCJHKYLPFMDXLQJJSMTQGZSJLQDLDGJYCALCMZCSDJLLNXDJFFFFJCZFMZFFPFKHKGDPSXKTACJDHHZDDCRRCFQYJKQCCWJDXHWJLYLLZGCFCQDSMLZPBJJPLSBCJGGDCKKDEZSQCCKJGCGKDJTJDLZYCXKLQSCGJCLTFPCQCZGWPJDQYZJJBYJHSJDZWGFSJGZKQCCZLLPSPKJGQJHZZLJPLGJGJJTHJJYJZCZMLZLYQBGJWMLJKXZDZNJQSYZMLJLLJKYWXMKJLHSKJGBMCLYYMKXJQLBMLLKMDXXKWYXYSLMLPSJQQJQXYXFJTJDXMXXLLCXQBSYJBGWYMBGGBCYXPJYGPEPFGDJGBHBNSQJYZJKJKHXQFGQZKFHYGKHDKLLSDJQXPQYKYBNQSXQNSZSWHBSXWHXWBZZXDMNSJBSBKBBZKLYLXGWXDRWYQZMYWSJQLCJXXJXKJEQXSCYETLZHLYYYSDZPAQYZCMTLSHTZCFYZYXYLJSDCJQAGYSLCQLYYYSHMRQQKLDXZSCSSSYDYCJYSFSJBFRSSZQSBXXPXJYSDRCKGJLGDKZJZBDKTCSYQPYHSTCLDJDHMXMCGXYZHJDDTMHLTXZXYLYMOHYJCLTYFBQQXPFBDFHHTKSQHZYYWCNXXCRWHOWGYJLEGWDQCWGFJYCSNTMYTOLBYGWQWESJPWNMLRYDZSZTXYQPZGCWXHNGPYXSHMYQJXZTDPPBFYHZHTJYFDZWKGKZBLDNTSXHQEEGZZYLZMMZYJZGXZXKHKSTXNXXWYLYAPSTHXDWHZYMPXAGKYDXBHNHXKDPJNMYHYLPMGOCSLNZHKXXLPZZLBMLSFBHHGYGYYGGBHSCYAQTYWLXTZQCEZYDQDQMMHTKLLSZHLSJZWFYHQSWSCWLQAZYNYTLSXTHAZNKZZSZZLAXXZWWCTGQQTDDYZTCCHYQZFLXPSLZYGPZSZNGLNDQTBDLXGTCTAJDKYWNSYZLJHHZZCWNYYZYWMHYCHHYXHJKZWSXHZYXLYSKQYSPSLYZWMYPPKBYGLKZHTYXAXQSYSHXASMCHKDSCRSWJPWXSGZJLWWSCHSJHSQNHCSEGNDAQTBAALZZMSSTDQJCJKTSCJAXPLGGXHHGXXZCXPDMMHLDGTYBYSJMXHMRCPXXJZCKZXSHMLQXXTTHXWZFKHCCZDYTCJYXQHLXDHYPJQXYLSYYDZOZJNYXQEZYSQYAYXWYPDGXDDXSPPYZNDLTWRHXYDXZZJHTCXMCZLHPYYYYMHZLLHNXMYLLLMDCPPXHMXDKYCYRDLTXJCHHZZXZLCCLYLNZSHZJZZLNNRLWHYQSNJHXYNTTTKYJPYCHHYEGKCTTWLGQRLGGTGTYGYHPYHYLQYQGCWYQKPYYYTTTTLHYHLLTYTTSPLKYZXGZWGPYDSSZZDQXSKCQNMJJZZBXYQMJRTFFBTKHZKBXLJJKDXJTLBWFZPPTKQTZTGPDGNTPJYFALQMKGXBDCLZFHZCLLLLADPMXDJHLCCLGYHDZFGYDDGCYYFGYDXKSSEBDHYKDKDKHNAXXYBPBYYHXZQGAFFQYJXDMLJCSQZLLPCHBSXGJYNDYBYQSPZWJLZKSDDTACTBXZDYZYPJZQSJNKKTKNJDJGYYPGTLFYQKASDNTCYHBLWDZHBBYDWJRYGKZYHEYYFJMSDTYFZJJHGCXPLXHLDWXXJKYTCYKSSSMTWCTTQZLPBSZDZWZXGZAGYKTYWXLHLSPBCLLOQMMZSSLCMBJCSZZKYDCZJGQQDSMCYTZQQLWZQZXSSFPTTFQMDDZDSHDTDWFHTDYZJYQJQKYPBDJYYXTLJHDRQXXXHAYDHRJLKLYTWHLLRLLRCXYLBWSRSZZSYMKZZHHKYHXKSMDSYDYCJPBZBSQLFCXXXNXKXWYWSDZYQOGGQMMYHCDZTTFJYYBGSTTTYBYKJDHKYXBELHTYPJQNFXFDYKZHQKZBYJTZBXHFDXKDASWTAWAJLDYJSFHBLDNNTNQJTJNCHXFJSRFWHZFMDRYJYJWZPDJKZYJYMPCYZNYNXFBYTFYFWYGDBNZZZDNYTXZEMMQBSQEHXFZMBMFLZZSRXYMJGSXWZJSPRYDJSJGXHJJGLJJYNZZJXHGXKYMLPYYYCXYTWQZSWHWLYRJLPXSLSXMFSWWKLCTNXNYNPSJSZHDZEPTXMYYWXYYSYWLXJQZQXZDCLEEELMCPJPCLWBXSQHFWWTFFJTNQJHJQDXHWLBYZNFJLALKYYJLDXHHYCSTYYWNRJYXYWTRMDRQHWQCMFJDYZMHMYYXJWMYZQZXTLMRSPWWCHAQBXYGZYPXYYRRCLMPYMGKSJSZYSRMYJSNXTPLNBAPPYPYLXYYZKYNLDZYJZCZNNLMZHHARQMPGWQTZMXXMLLHGDZXYHXKYXYCJMFFYYHJFSBSSQLXXNDYCANNMTCJCYPRRNYTYQNYYMBMSXNDLYLYSLJRLXYSXQMLLYZLZJJJKYZZCSFBZXXMSTBJGNXYZHLXNMCWSCYZYFZLXBRNNNYLBNRTGZQYSATSWRYHYJZMZDHZGZDWYBSSCSKXSYHYTXXGCQGXZZSHYXJSCRHMKKBXCZJYJYMKQHZJFNBHMQHYSNJNZYBKNQMCLGQHWLZNZSWXKHLJHYYBQLBFCDSXDLDSPFZPSKJYZWZXZDDXJSMMEGJSCSSMGCLXXKYYYLNYPWWWGYDKZJGGGZGGSYCKNJWNJPCXBJJTQTJWDSSPJXZXNZXUMELPXFSXTLLXCLJXJJLJZXCTPSWXLYDHLYQRWHSYCSQYYBYAYWJJJQFWQCQQCJQGXALDBZZYJGKGXPLTZYFXJLTPADKYQHPMATLCPDCKBMTXYBHKLENXDLEEGQDYMSAWHZMLJTWYGXLYQZLJEEYYBQQFFNLYXRDSCTGJGXYYNKLLYQKCCTLHJLQMKKZGCYYGLLLJDZGYDHZWXPYSJBZKDZGYZZHYWYFQYTYZSZYEZZLYMHJJHTSMQWYZLKYYWZCSRKQYTLTDXWCTYJKLWSQZWBDCQYNCJSRSZJLKCDCDTLZZZACQQZZDDXYPLXZBQJYLZLLLQDDZQJYJYJZYXNYYYNYJXKXDAZWYRDLJYYYRJLXLLDYXJCYWYWNQCCLDDNYYYNYCKCZHXXCCLGZQJGKWPPCQQJYSBZZXYJSQPXJPZBSBDSFNSFPZXHDWZTDWPPTFLZZBZDMYYPQJRSDZSQZSQXBDGCPZSWDWCSQZGMDHZXMWWFYBPDGPHTMJTHZSMMBGZMBZJCFZWFZBBZMQCFMBDMCJXLGPNJBBXGYHYYJGPTZGZMQBQTCGYXJXLWZKYDPDYMGCFTPFXYZTZXDZXTGKMTYBBCLBJASKYTSSQYYMSZXFJEWLXLLSZBQJJJAKLYLXLYCCTSXMCWFKKKBSXLLLLJYXTYLTJYYTDPJHNHNNKBYQNFQYYZBYYESSESSGDYHFHWTCJBSDZZTFDMXHCNJZYMQWSRYJDZJQPDQBBSTJGGFBKJBXTGQHNGWJXJGDLLTHZHHYYYYYYSXWTYYYCCBDBPYPZYCCZYJPZYWCBDLFWZCWJDXXHYHLHWZZXJTCZLCDPXUJCZZZLYXJJTXPHFXWPYWXZPTDZZBDZCYHJHMLXBQXSBYLRDTGJRRCTTTHYTCZWMXFYTWWZCWJWXJYWCSKYBZSCCTZQNHXNWXXKHKFHTSWOCCJYBCMPZZYKBNNZPBZHHZDLSYDDYTYFJPXYNGFXBYQXCBHXCPSXTYZDMKYSNXSXLHKMZXLYHDHKWHXXSSKQYHHCJYXGLHZXCSNHEKDTGZXQYPKDHEXTYKCNYMYYYPKQYYYKXZLTHJQTBYQHXBMYHSQCKWWYLLHCYYLNNEQXQWMCFBDCCMLJGGXDQKTLXKGNQCDGZJWYJJLYHHQTTTNWCHMXCXWHWSZJYDJCCDBQCDGDNYXZTHCQRXCBHZTQCBXWGQWYYBXHMBYMYQTYEXMQKYAQYRGYZSLFYKKQHYSSQYSHJGJCNXKZYCXSBXYXHYYLSTYCXQTHYSMGSCPMMGCCCCCMTZTASMGQZJHKLOSQYLSWTMXSYQKDZLJQQYPLSYCZTCQQPBBQJZCLPKHQZYYXXDTDDTSJCXFFLLCHQXMJLWCJCXTSPYCXNDTJSHJWXDQQJSKXYAMYLSJHMLALYKXCYYDMNMDQMXMCZNNCYBZKKYFLMCHCMLHXRCJJHSYLNMTJZGZGYWJXSRXCWJGJQHQZDQJDCJJZKJKGDZQGJJYJYLXZXXCDQHHHEYTMHLFSBDJSYYSHFYSTCZQLPBDRFRZTZYKYWHSZYQKWDQZRKMSYNBCRXQBJYFAZPZZEDZCJYWBCJWHYJBQSZYWRYSZPTDKZPFPBNZTKLQYHBBZPNPPTYZZYBQNYDCPJMMCYCQMCYFZZDCMNLFPBPLNGQJTBTTNJZPZBBZNJKLJQYLNBZQHKSJZNGGQSZZKYXSHPZSNBCGZKDDZQANZHJKDRTLZLSWJLJZLYWTJNDJZJHXYAYNCBGTZCSSQMNJPJYTYSWXZFKWJQTKHTZPLBHSNJZSYZBWZZZZLSYLSBJHDWWQPSLMMFBJDWAQYZTCJTBNNWZXQXCDSLQGDSDPDZHJTQQPSWLYYJZLGYXYZLCTCBJTKTYCZJTQKBSJLGMGZDMCSGPYNJZYQYYKNXRPWSZXMTNCSZZYXYBYHYZAXYWQCJTLLCKJJTJHGDXDXYQYZZBYWDLWQCGLZGJGQRQZCZSSBCRPCSKYDZNXJSQGXSSJMYDNSTZTPBDLTKZWXQWQTZEXNQCZGWEZKSSBYBRTSSSLCCGBPSZQSZLCCGLLLZXHZQTHCZMQGYZQZNMCOCSZJMMZSQPJYGQLJYJPPLDXRGZYXCCSXHSHGTZNLZWZKJCXTCFCJXLBMQBCZZWPQDNHXLJCTHYZLGYLNLSZZPCXDSCQQHJQKSXZPBAJYEMSMJTZDXLCJYRYYNWJBNGZZTMJXLTBSLYRZPYLSSCNXPHLLHYLLQQZQLXYMRSYCXZLMMCZLTZSDWTJJLLNZGGQXPFSKYGYGHBFZPDKMWGHCXMSGDXJMCJZDYCABXJDLNBCDQYGSKYDQTXDJJYXMSZQAZDZFSLQXYJSJZYLBTXXWXQQZBJZUFBBLYLWDSLJHXJYZJWTDJCZFQZQZZDZSXZZQLZCDZFJHYSPYMPQZMLPPLFFXJJNZZYLSJEYQZFPFZKSYWJJJHRDJZZXTXXGLGHYDXCSKYSWMMZCWYBAZBJKSHFHJCXMHFQHYXXYZFTSJYZFXYXPZLCHMZMBXHZZSXYFYMNCWDABAZLXKTCSHHXKXJJZJSTHYGXSXYYHHHJWXKZXSSBZZWHHHCWTZZZPJXSNXQQJGZYZYWLLCWXZFXXYXYHXMKYYSWSQMNLNAYCYSPMJKHWCQHYLAJJMZXHMMCNZHBHXCLXTJPLTXYJHDYYLTTXFSZHYXXSJBJYAYRSMXYPLCKDUYHLXRLNLLSTYZYYQYGYHHSCCSMZCTZQXKYQFPYYRPFFLKQUNTSZLLZMWWTCQQYZWTLLMLMPWMBZSSTZRBPDDTLQJJBXZCSRZQQYGWCSXFWZLXCCRSZDZMCYGGDZQSGTJSWLJMYMMZYHFBJDGYXCCPSHXNZCSBSJYJGJMPPWAFFYFNXHYZXZYLREMZGZCYZSSZDLLJCSQFNXZKPTXZGXJJGFMYYYSNBTYLBNLHPFZDCYFBMGQRRSSSZXYSGTZRNYDZZCDGPJAFJFZKNZBLCZSZPSGCYCJSZLMLRSZBZZLDLSLLYSXSQZQLYXZLSKKBRXBRBZCYCXZZZEEYFGKLZLYYHGZSGZLFJHGTGWKRAAJYZKZQTSSHJJXDCYZUYJLZYRZDQQHGJZXSSZBYKJPBFRTJXLLFQWJHYLQTYMBLPZDXTZYGBDHZZRBGXHWNJTJXLKSCFSMWLSDQYSJTXKZSCFWJLBXFTZLLJZLLQBLSQMQQCGCZFPBPHZCZJLPYYGGDTGWDCFCZQYYYQYSSCLXZSKLZZZGFFCQNWGLHQYZJJCZLQZZYJPJZZBPDCCMHJGXDQDGDLZQMFGPSYTSDYFWWDJZJYSXYYCZCYHZWPBYKXRYLYBHKJKSFXTZJMMCKHLLTNYYMSYXYZPYJQYCSYCWMTJJKQYRHLLQXPSGTLYYCLJSCPXJYZFNMLRGJJTYZBXYZMSJYJHHFZQMSYXRSZCWTLRTQZSSTKXGQKGSPTGCZNJSJCQCXHMXGGZTQYDJKZDLBZSXJLHYQGGGTHQSZPYHJHHGYYGKGGCWJZZYLCZLXQSFTGZSLLLMLJSKCTBLLZZSZMMNYTPZSXQHJCJYQXYZXZQZCPSHKZZYSXCDFGMWQRLLQXRFZTLYSTCTMJCXJJXHJNXTNRZTZFQYHQGLLGCXSZSJDJLJCYDSJTLNYXHSZXCGJZYQPYLFHDJSBPCCZHJJJQZJQDYBSSLLCMYTTMQTBHJQNNYGKYRQYQMZGCJKPDCGMYZHQLLSLLCLMHOLZGDYYFZSLJCQZLYLZQJESHNYLLJXGJXLYSYYYXNBZLJSSZCQQCJYLLZLTJYLLZLLBNYLGQCHXYYXOXCXQKYJXXXYKLXSXXYQXCYKQXQCSGYXXYQXYGYTQOHXHXPYXXXULCYEYCHZZCBWQBBWJQZSCSZSSLZYLKDESJZWMYMCYTSDSXXSCJPQQSQYLYYZYCMDJDZYWCBTJSYDJKCYDDJLBDJJSODZYSYXQQYXDHHGQQYQHDYXWGMMMAJDYBBBPPBCMUUPLJZSMTXERXJMHQNUTPJDCBSSMSSSTKJTSSMMTRCPLZSZMLQDSDMJMQPNQDXCFYNBFSDQXYXHYAYKQYDDLQYYYSSZBYDSLNTFQTZQPZMCHDHCZCWFDXTMYQSPHQYYXSRGJCWTJTZZQMGWJJTJHTQJBBHWZPXXHYQFXXQYWYYHYSCDYDHHQMNMTMWCPBSZPPZZGLMZFOLLCFWHMMSJZTTDHZZYFFYTZZGZYSKYJXQYJZQBHMBZZLYGHGFMSHPZFZSNCLPBQSNJXZSLXXFPMTYJYGBXLLDLXPZJYZJYHHZCYWHJYLSJEXFSZZYWXKZJLUYDTMLYMQJPWXYHXSKTQJEZRPXXZHHMHWQPWQLYJJQJJZSZCPHJLCHHNXJLQWZJHBMZYXBDHHYPZLHLHLGFWLCHYYTLHJXCJMSCPXSTKPNHQXSRTYXXTESYJCTLSSLSTDLLLWWYHDHRJZSFGXTSYCZYNYHTDHWJSLHTZDQDJZXXQHGYLTZPHCSQFCLNJTCLZPFSTPDYNYLGMJLLYCQHYSSHCHYLHQYQTMZYPBYWRFQYKQSYSLZDQJMPXYYSSRHZJNYWTQDFZBWWTWWRXCWHGYHXMKMYYYQMSMZHNGCEPMLQQMTCWCTMMPXJPJJHFXYYZSXZHTYBMSTSYJTTQQQYYLHYNPYQZLCYZHZWSMYLKFJXLWGXYPJYTYSYXYMZCKTTWLKSMZSYLMPWLZWXWQZSSAQSYXYRHSSNTSRAPXCPWCMGDXHXZDZYFJHGZTTSBJHGYZSZYSMYCLLLXBTYXHBBZJKSSDMALXHYCFYGMQYPJYCQXJLLLJGSLZGQLYCJCCZOTYXMTMTTLLWTGPXYMZMKLPSZZZXHKQYSXCTYJZYHXSHYXZKXLZWPSQPYHJWPJPWXQQYLXSDHMRSLZZYZWTTCYXYSZZSHBSCCSTPLWSSCJCHNLCGCHSSPHYLHFHHXJSXYLLNYLSZDHZXYLSXLWZYKCLDYAXZCMDDYSPJTQJZLNWQPSSSWCTSTSZLBLNXSMNYYMJQBQHRZWTYYDCHQLXKPZWBGQYBKFCMZWPZLLYYLSZYDWHXPSBCMLJBSCGBHXLQHYRLJXYSWXWXZSLDFHLSLYNJLZYFLYJYCDRJLFSYZFSLLCQYQFGJYHYXZLYLMSTDJCYHBZLLNWLXXYGYYHSMGDHXXHHLZZJZXCZZZCYQZFNGWPYLCPKPYYPMCLQKDGXZGGWQBDXZZKZFBXXLZXJTPJPTTBYTSZZDWSLCHZHSLTYXHQLHYXXXYYZYSWTXZKHLXZXZPYHGCHKCFSYHUTJRLXFJXPTZTWHPLYXFCRHXSHXKYXXYHZQDXQWULHYHMJTBFLKHTXCWHJFWJCFPQRYQXCYYYQYGRPYWSGSUNGWCHKZDXYFLXXHJJBYZWTSXXNCYJJYMSWZJQRMHXZWFQSYLZJZGBHYNSLBGTTCSYBYXXWXYHXYYXNSQYXMQYWRGYQLXBBZLJSYLPSYTJZYHYZAWLRORJMKSCZJXXXYXCHDYXRYXXJDTSQFXLYLTSFFYXLMTYJMJUYYYXLTZCSXQZQHZXLYYXZHDNBRXXXJCTYHLBRLMBRLLAXKYLLLJLYXXLYCRYLCJTGJCMTLZLLCYZZPZPCYAWHJJFYBDYYZSMPCKZDQYQPBPCJPDCYZMDPBCYYDYCNNPLMTMLRMFMMGWYZBSJGYGSMZQQQZTXMKQWGXLLPJGZBQCDJJJFPKJKCXBLJMSWMDTQJXLDLPPBXCWRCQFBFQJCZAHZGMYKPHYYHZYKNDKZMBPJYXPXYHLFPNYYGXJDBKXNXHJMZJXSTRSTLDXSKZYSYBZXJLXYSLBZYSLHXJPFXPQNBYLLJQKYGZMCYZZYMCCSLCLHZFWFWYXZMWSXTYNXJHPYYMCYSPMHYSMYDYSHQYZCHMJJMZCAAGCFJBBHPLYZYLXXSDJGXDHKXXTXXNBHRMLYJSLTXMRHNLXQJXYZLLYSWQGDLBJHDCGJYQYCMHWFMJYBMBYJYJWYMDPWHXQLDYGPDFXXBCGJSPCKRSSYZJMSLBZZJFLJJJLGXZGYXYXLSZQYXBEXYXHGCXBPLDYHWETTWWCJMBTXCHXYQXLLXFLYXLLJLSSFWDPZSMYJCLMWYTCZPCHQEKCQBWLCQYDPLQPPQZQFJQDJHYMMCXTXDRMJWRHXCJZYLQXDYYNHYYHRSLSRSYWWZJYMTLTLLGTQCJZYABTCKZCJYCCQLJZQXALMZYHYWLWDXZXQDLLQSHGPJFJLJHJABCQZDJGTKHSSTCYJLPSWZLXZXRWGLDLZRLZXTGSLLLLZLYXXWGDZYGBDPHZPBRLWSXQBPFDWOFMWHLYPCBJCCLDMBZPBZZLCYQXLDOMZBLZWPDWYYGDSTTHCSQSCCRSSSYSLFYBFNTYJSZDFNDPDHDZZMBBLSLCMYFFGTJJQWFTMTPJWFNLBZCMMJTGBDZLQLPYFHYYMJYLSDCHDZJWJCCTLJCLDTLJJCPDDSQDSSZYBNDBJLGGJZXSXNLYCYBJXQYCBYLZCFZPPGKCXZDZFZTJJFJSJXZBNZYJQTTYJYHTYCZHYMDJXTTMPXSPLZCDWSLSHXYPZGTFMLCJTYCBPMGDKWYCYZCDSZZYHFLYCTYGWHKJYYLSJCXGYWJCBLLCSNDDBTZBSCLYZCZZSSQDLLMQYYHFSLQLLXFTYHABXGWNYWYYPLLSDLDLLBJCYXJZMLHLJDXYYQYTDLLLBUGBFDFBBQJZZMDPJHGCLGMJJPGAEHHBWCQXAXHHHZCHXYPHJAXHLPHJPGPZJQCQZGJJZZUZDMQYYBZZPHYHYBWHAZYJHYKFGDPFQSDLZMLJXKXGALXZDAGLMDGXMWZQYXXDXXPFDMMSSYMPFMDMMKXKSYZYSHDZKXSYSMMZZZMSYDNZZCZXFPLSTMZDNMXCKJMZTYYMZMZZMSXHHDCZJEMXXKLJSTLWLSQLYJZLLZJSSDPPMHNLZJCZYHMXXHGZCJMDHXTKGRMXFWMCGMWKDTKSXQMMMFZZYDKMSCLCMPCGMHSPXQPZDSSLCXKYXTWLWJYAHZJGZQMCSNXYYMMPMLKJXMHLMLQMXCTKZMJQYSZJSYSZHSYJZJCDAJZYBSDQJZGWZQQXFKDMSDJLFWEHKZQKJPEYPZYSZCDWYJFFMZZYLTTDZZEFMZLBNPPLPLPEPSZALLTYLKCKQZKGENQLWAGYXYDPXLHSXQQWQCQXQCLHYXXMLYCCWLYMQYSKGCHLCJNSZKPYZKCQZQLJPDMDZHLASXLBYDWQLWDNBQCRYDDZTJYBKBWSZDXDTNPJDTCTQDFXQQMGNXECLTTBKPWSLCTYQLPWYZZKLPYGZCQQPLLKCCYLPQMZCZQCLJSLQZDJXLDDHPZQDLJJXZQDXYZQKZLJCYQDYJPPYPQYKJYRMPCBYMCXKLLZLLFQPYLLLMBSGLCYSSLRSYSQTMXYXZQZFDZUYSYZTFFMZZSMZQHZSSCCMLYXWTPZGXZJGZGSJSGKDDHTQGGZLLBJDZLCBCHYXYZHZFYWXYZYMSDBZZYJGTSMTFXQYXQSTDGSLNXDLRYZZLRYYLXQHTXSRTZNGZXBNQQZFMYKMZJBZYMKBPNLYZPBLMCNQYZZZSJZHJCTZKHYZZJRDYZHNPXGLFZTLKGJTCTSSYLLGZRZBBQZZKLPKLCZYSSUYXBJFPNJZZXCDWXZYJXZZDJJKGGRSRJKMSMZJLSJYWQSKYHQJSXPJZZZLSNSHRNYPZTWCHKLPSRZLZXYJQXQKYSJYCZTLQZYBBYBWZPQDWWYZCYTJCJXCKCWDKKZXSGKDZXWWYYJQYYTCYTDLLXWKCZKKLCCLZCQQDZLQLCSFQCHQHSFSMQZZLNBJJZBSJHTSZDYSJQJPDLZCDCWJKJZZLPYCGMZWDJJBSJQZSYZYHHXJPBJYDSSXDZNCGLQMBTSFSBPDZDLZNFGFJGFSMPXJQLMBLGQCYYXBQKDJJQYRFKZTJDHCZKLBSDZCFJTPLLJGXHYXZCSSZZXSTJYGKGCKGYOQXJPLZPBPGTGYJZGHZQZZLBJLSQFZGKQQJZGYCZBZQTLDXRJXBSXXPZXHYZYCLWDXJJHXMFDZPFZHQHQMQGKSLYHTYCGFRZGNQXCLPDLBZCSCZQLLJBLHBZCYPZZPPDYMZZSGYHCKCPZJGSLJLNSCDSLDLXBMSTLDDFJMKDJDHZLZXLSZQPQPGJLLYBDSZGQLBZLSLKYYHZTTNTJYQTZZPSZQZTLLJTYYLLQLLQYZQLBDZLSLYYZYMDFSZSNHLXZNCZQZPBWSKRFBSYZMTHBLGJPMCZZLSTLXSHTCSYZLZBLFEQHLXFLCJLYLJQCBZLZJHHSSTBRMHXZHJZCLXFNBGXGTQJCZTMSFZKJMSSNXLJKBHSJXNTNLZDNTLMSJXGZJYJCZXYJYJWRWWQNZTNFJSZPZSHZJFYRDJSFSZJZBJFZQZZHZLXFYSBZQLZSGYFTZDCSZXZJBQMSZKJRHYJZCKMJKHCHGTXKXQGLXPXFXTRTYLXJXHDTSJXHJZJXZWZLCQSBTXWXGXTXXHXFTSDKFJHZYJFJXRZSDLLLTQSQQZQWZXSYQTWGWBZCGZLLYZBCLMQQTZHZXZXLJFRMYZFLXYSQXXJKXRMQDZDMMYYBSQBHGZMWFWXGMXLZPYYTGZYCCDXYZXYWGSYJYZNBHPZJSQSYXSXRTFYZGRHZTXSZZTHCBFCLSYXZLZQMZLMPLMXZJXSFLBYZMYQHXJSXRXSQZZZSSLYFRCZJRCRXHHZXQYDYHXSJJHZCXZBTYNSYSXJBQLPXZQPYMLXZKYXLXCJLCYSXXZZLXDLLLJJYHZXGYJWKJRWYHCPSGNRZLFZWFZZNSXGXFLZSXZZZBFCSYJDBRJKRDHHGXJLJJTGXJXXSTJTJXLYXQFCSGSWMSBCTLQZZWLZZKXJMLTMJYHSDDBXGZHDLBMYJFRZFSGCLYJBPMLYSMSXLSZJQQHJZFXGFQFQBPXZGYYQXGZTCQWYLTLGWSGWHRLFSFGZJMGMGBGTJFSYZZGZYZAFLSSPMLPFLCWBJZCLJJMZLPJJLYMQDMYYYFBGYGYZMLYZDXQYXRQQQHSYYYQXYLJTYXFSFSLLGNQCYHYCWFHCCCFXPYLYPLLZYXXXXXKQHHXSHJZCFZSCZJXCPZWHHHHHAPYLQALPQAFYHXDYLUKMZQGGGDDESRNNZLTZGCHYPPYSQJJHCLLJTOLNJPZLJLHYMHEYDYDSQYCDDHGZUNDZCLZYZLLZNTNYZGSLHSLPJJBDGWXPCDUTJCKLKCLWKLLCASSTKZZDNQNTTLYYZSSYSSZZRYLJQKCQDHHCRXRZYDGRGCWCGZQFFFPPJFZYNAKRGYWYQPQXXFKJTSZZXSWZDDFBBXTBGTZKZNPZZPZXZPJSZBMQHKCYXYLDKLJNYPKYGHGDZJXXEAHPNZKZTZCMXCXMMJXNKSZQNMNLWBWWXJKYHCPSTMCSQTZJYXTPCTPDTNNPGLLLZSJLSPBLPLQHDTNJNLYYRSZFFJFQWDPHZDWMRZCCLODAXNSSNYZRESTYJWJYJDBCFXNMWTTBYLWSTSZGYBLJPXGLBOCLHPCBJLTMXZLJYLZXCLTPNCLCKXTPZJSWCYXSFYSZDKNTLBYJCYJLLSTGQCBXRYZXBXKLYLHZLQZLNZCXWJZLJZJNCJHXMNZZGJZZXTZJXYCYYCXXJYYXJJXSSSJSTSSTTPPGQTCSXWZDCSYFPTFBFHFBBLZJCLZZDBXGCXLQPXKFZFLSYLTUWBMQJHSZBMDDBCYSCCLDXYCDDQLYJJWMQLLCSGLJJSYFPYYCCYLTJANTJJPWYCMMGQYYSXDXQMZHSZXPFTWWZQSWQRFKJLZJQQYFBRXJHHFWJJZYQAZMYFRHCYYBYQWLPEXCCZSTYRLTTDMQLYKMBBGMYYJPRKZNPBSXYXBHYZDJDNGHPMFSGMWFZMFQMMBCMZZCJJLCNUXYQLMLRYGQZCYXZLWJGCJCGGMCJNFYZZJHYCPRRCMTZQZXHFQGTJXCCJEAQCRJYHPLQLSZDJRBCQHQDYRHYLYXJSYMHZYDWLDFRYHBPYDTSSCNWBXGLPZMLZZTQSSCPJMXXYCSJYTYCGHYCJWYRXXLFEMWJNMKLLSWTXHYYYNCMMCWJDQDJZGLLJWJRKHPZGGFLCCSCZMCBLTBHBQJXQDSPDJZZGKGLFQYWBZYZJLTSTDHQHCTCBCHFLQMPWDSHYYTQWCNZZJTLBYMBPDYYYXSQKXWYYFLXXNCWCXYPMAELYKKJMZZZBRXYYQJFLJPFHHHYTZZXSGQQMHSPGDZQWBWPJHZJDYSCQWZKTXXSQLZYYMYSDZGRXCKKUJLWPYSYSCSYZLRMLQSYLJXBCXTLWDQZPCYCYKPPPNSXFYZJJRCEMHSZMSXLXGLRWGCSTLRSXBZGBZGZTCPLUJLSLYLYMTXMTZPALZXPXJTJWTCYYZLBLXBZLQMYLXPGHDSLSSDMXMBDZZSXWHAMLCZCPJMCNHJYSNSYGCHSKQMZZQDLLKABLWJXSFMOCDXJRRLYQZKJMYBYQLYHETFJZFRFKSRYXFJTWDSXXSYSQJYSLYXWJHSNLXYYXHBHAWHHJZXWMYLJCSSLKYDZTXBZSYFDXGXZJKHSXXYBSSXDPYNZWRPTQZCZENYGCXQFJYKJBZMLJCMQQXUOXSLYXXLYLLJDZBTYMHPFSTTQQWLHOKYBLZZALZXQLHZWRRQHLSTMYPYXJJXMQSJFNBXYXYJXXYQYLTHYLQYFMLKLJTMLLHSZWKZHLJMLHLJKLJSTLQXYLMBHHLNLZXQJHXCFXXLHYHJJGBYZZKBXSCQDJQDSUJZYYHZHHMGSXCSYMXFEBCQWWRBPYYJQTYZCYQYQQZYHMWFFHGZFRJFCDPXNTQYZPDYKHJLFRZXPPXZDBBGZQSTLGDGYLCQMLCHHMFYWLZYXKJLYPQHSYWMQQGQZMLZJNSQXJQSYJYCBEHSXFSZPXZWFLLBCYYJDYTDTHWZSFJMQQYJLMQXXLLDTTKHHYBFPWTYYSQQWNQWLGWDEBZWCMYGCULKJXTMXMYJSXHYBRWFYMWFRXYQMXYSZTZZTFYKMLDHQDXWYYNLCRYJBLPSXCXYWLSPRRJWXHQYPHTYDNXHHMMYWYTZCSQMTSSCCDALWZTCPQPYJLLQZYJSWXMZZMMYLMXCLMXCZMXMZSQTZPPQQBLPGXQZHFLJJHYTJSRXWZXSCCDLXTYJDCQJXSLQYCLZXLZZXMXQRJMHRHZJBHMFLJLMLCLQNLDXZLLLPYPSYJYSXCQQDCMQJZZXHNPNXZMEKMXHYKYQLXSXTXJYYHWDCWDZHQYYBGYBCYSCFGPSJNZDYZZJZXRZRQJJYMCANYRJTLDPPYZBSTJKXXZYPFDWFGZZRPYMTNGXZQBYXNBUFNQKRJQZMJEGRZGYCLKXZDSKKNSXKCLJSPJYYZLQQJYBZSSQLLLKJXTBKTYLCCDDBLSPPFYLGYDTZJYQGGKQTTFZXBDKTYYHYBBFYTYYBCLPDYTGDHRYRNJSPTCSNYJQHKLLLZSLYDXXWBCJQSPXBPJZJCJDZFFXXBRMLAZHCSNDLBJDSZBLPRZTSWSBXBCLLXXLZDJZSJPYLYXXYFTFFFBHJJXGBYXJPMMMPSSJZJMTLYZJXSWXTYLEDQPJMYGQZJGDJLQJWJQLLSJGJGYGMSCLJJXDTYGJQJQJCJZCJGDZZSXQGSJGGCXHQXSNQLZZBXHSGZXCXYLJXYXYYDFQQJHJFXDHCTXJYRXYSQTJXYEFYYSSYYJXNCYZXFXMSYSZXYYSCHSHXZZZGZZZGFJDLTYLNPZGYJYZYYQZPBXQBDZTZCZYXXYHHSQXSHDHGQHJHGYWSZTMZMLHYXGEBTYLZKQWYTJZRCLEKYSTDBCYKQQSAYXCJXWWGSBHJYZYDHCSJKQCXSWXFLTYNYZPZCCZJQTZWJQDZZZQZLJJXLSBHPYXXPSXSHHEZTXFPTLQYZZXHYTXNCFZYYHXGNXMYWXTZSJPTHHGYMXMXQZXTSBCZYJYXXTYYZYPCQLMMSZMJZZLLZXGXZAAJZYXJMZXWDXZSXZDZXLEYJJZQBHZWZZZQTZPSXZTDSXJJJZNYAZPHXYYSRNQDTHZHYYKYJHDZXZLSWCLYBZYECWCYCRYLCXNHZYDZYDYJDFRJJHTRSQTXYXJRJHOJYNXELXSFSFJZGHPZSXZSZDZCQZBYYKLSGSJHCZSHDGQGXYZGXCHXZJWYQWGYHKSSEQZZNDZFKWYSSTCLZSTSYMCDHJXXYWEYXCZAYDMPXMDSXYBSQMJMZJMTZQLPJYQZCGQHXJHHLXXHLHDLDJQCLDWBSXFZZYYSCHTYTYYBHECXHYKGJPXHHYZJFXHWHBDZFYZBCAPNPGNYDMSXHMMMMAMYNBYJTMPXYYMCTHJBZYFCGTYHWPHFTWZZEZSBZEGPFMTSKFTYCMHFLLHGPZJXZJGZJYXZSBBQSCZZLZCCSTPGXMJSFTCCZJZDJXCYBZLFCJSYZFGSZLYBCWZZBYZDZYPSWYJZXZBDSYUXLZZBZFYGCZXBZHZFTPBGZGEJBSTGKDMFHYZZJHZLLZZGJQZLSFDJSSCBZGPDLFZFZSZYZYZSYGCXSNXXCHCZXTZZLJFZGQSQYXZJQDCCZTQCDXZJYQJQCHXZTDLGSCXZSYQJQTZWLQDQZTQCHQQJZYEZZZPBWKDJFCJPZTYPQYQTTYNLMBDKTJZPQZQZZFPZSBNJLGYJDXJDZZKZGQKXDLPZJTCJDQBXDJQJSTCKNXBXZMSLYJCQMTJQWWCJQNJNLLLHJCWQTBZQYDZCZPZZDZYDDCYZZZCCJTTJFZDPRRTZTJDCQTQZDTJNPLZBCLLCTZSXKJZQZPZLBZRBTJDCXFCZDBCCJJLTQQPLDCGZDBBZJCQDCJWYNLLZYZCCDWLLXWZLXRXNTQQCZXKQLSGDFQTDDGLRLAJJTKUYMKQLLTZYTDYYCZGJWYXDXFRSKSTQTENQMRKQZHHQKDLDAZFKYPBGGPZREBZZYKZZSPEGJXGYKQZZZSLYSYYYZWFQZYLZZLZHWCHKYPQGNPGBLPLRRJYXCCSYYHSFZFYBZYYTGZXYLXCZWXXZJZBLFFLGSKHYJZEYJHLPLLLLCZGXDRZELRHGKLZZYHZLYQSZZJZQLJZFLNBHGWLCZCFJYSPYXZLZLXGCCPZBLLCYBBBBUBBCBPCRNNZCZYRBFSRLDCGQYYQXYGMQZWTZYTYJXYFWTEHZZJYWLCCNTZYJJZDEDPZDZTSYQJHDYMBJNYJZLXTSSTPHNDJXXBYXQTZQDDTJTDYYTGWSCSZQFLSHLGLBCZPHDLYZJYCKWTYTYLBNYTSDSYCCTYSZYYEBHEXHQDTWNYGYCLXTSZYSTQMYGZAZCCSZZDSLZCLZRQXYYELJSBYMXSXZTEMBBLLYYLLYTDQYSHYMRQWKFKBFXNXSBYCHXBWJYHTQBPBSBWDZYLKGZSKYHXQZJXHXJXGNLJKZLYYCDXLFYFGHLJGJYBXQLYBXQPQGZTZPLNCYPXDJYQYDYMRBESJYYHKXXSTMXRCZZYWXYQYBMCLLYZHQYZWQXDBXBZWZMSLPDMYSKFMZKLZCYQYCZLQXFZZYDQZPZYGYJYZMZXDZFYFYTTQTZHGSPCZMLCCYTZXJCYTJMKSLPZHYSNZLLYTPZCTZZCKTXDHXXTQCYFKSMQCCYYAZHTJPCYLZLYJBJXTPNYLJYYNRXSYLMMNXJSMYBCSYSYLZYLXJJQYLDZLPQBFZZBLFNDXQKCZFYWHGQMRDSXYCYTXNQQJZYYPFZXDYZFPRXEJDGYQBXRCNFYYQPGHYJDYZXGRHTKYLNWDZNTSMPKLBTHBPYSZBZTJZSZZJTYYXZPHSSZZBZCZPTQFZMYFLYPYBBJQXZMXXDJMTSYSKKBJZXHJCKLPSMKYJZCXTMLJYXRZZQSLXXQPYZXMKYXXXJCLJPRMYYGADYSKQLSNDHYZKQXZYZTCGHZTLMLWZYBWSYCTBHJHJFCWZTXWYTKZLXQSHLYJZJXTMPLPYCGLTBZZTLZJCYJGDTCLKLPLLQPJMZPAPXYZLKKTKDZCZZBNZDYDYQZJYJGMCTXLTGXSZLMLHBGLKFWNWZHDXUHLFMKYSLGXDTWWFRJEJZTZHYDXYKSHWFZCQSHKTMQQHTZHYMJDJSKHXZJZBZZXYMPAGQMSTPXLSKLZYNWRTSQLSZBPSPSGZWYHTLKSSSWHZZLYYTNXJGMJSZSUFWNLSOZTXGXLSAMMLBWLDSZYLAKQCQCTMYCFJBSLXCLZZCLXXKSBZQCLHJPSQPLSXXCKSLNHPSFQQYTXYJZLQLDXZQJZDYYDJNZPTUZDSKJFSLJHYLZSQZLBTXYDGTQFDBYAZXDZHZJNHHQBYKNXJJQCZMLLJZKSPLDYCLBBLXKLELXJLBQYCXJXGCNLCQPLZLZYJTZLJGYZDZPLTQCSXFDMNYCXGBTJDCZNBGBQYQJWGKFHTNPYQZQGBKPBBYZMTJDYTBLSQMPSXTBNPDXKLEMYYCJYNZCTLDYKZZXDDXHQSHDGMZSJYCCTAYRZLPYLTLKXSLZCGGEXCLFXLKJRTLQJAQZNCMBYDKKCXGLCZJZXJHPTDJJMZQYKQSECQZDSHHADMLZFMMZBGNTJNNLGBYJBRBTMLBYJDZXLCJLPLDLPCQDHLXZLYCBLCXZZJADJLNZMMSSSMYBHBSQKBHRSXXJMXSDZNZPXLGBRHWGGFCXGMSKLLTSJYYCQLTSKYWYYHYWXBXQYWPYWYKQLSQPTNTKHQCWDQKTWPXXHCPTHTWUMSSYHBWCRWXHJMKMZNGWTMLKFGHKJYLSYYCXWHYECLQHKQHTTQKHFZLDXQWYZYYDESBPKYRZPJFYYZJCEQDZZDLATZBBFJLLCXDLMJSSXEGYGSJQXCWBXSSZPDYZCXDNYXPPZYDLYJCZPLTXLSXYZYRXCYYYDYLWWNZSAHJSYQYHGYWWAXTJZDAXYSRLTDPSSYYFNEJDXYZHLXLLLZQZSJNYQYQQXYJGHZGZCYJCHZLYCDSHWSHJZYJXCLLNXZJJYYXNFXMWFPYLCYLLABWDDHWDXJMCXZTZPMLQZHSFHZYNZTLLDYWLSLXHYMMYLMBWWKYXYADTXYLLDJPYBPWUXJMWMLLSAFDLLYFLBHHHBQQLTZJCQJLDJTFFKMMMBYTHYGDCQRDDWRQJXNBYSNWZDBYYTBJHPYBYTTJXAAHGQDQTMYSTQXKBTZPKJLZRBEQQSSMJJBDJOTGTBXPGBKTLHQXJJJCTHXQDWJLWRFWQGWSHCKRYSWGFTGYGBXSDWDWRFHWYTJJXXXJYZYSLPYYYPAYXHYDQKXSHXYXGSKQHYWFDDDPPLCJLQQEEWXKSYYKDYPLTJTHKJLTCYYHHJTTPLTZZCDLTHQKZXQYSTEEYWYYZYXXYYSTTJKLLPZMCYHQGXYHSRMBXPLLNQYDQHXSXXWGDQBSHYLLPJJJTHYJKYPPTHYYKTYEZYENMDSHLCRPQFDGFXZPSFTLJXXJBSWYYSKSFLXLPPLBBBLBSFXFYZBSJSSYLPBBFFFFSSCJDSTZSXZRYYSYFFSYZYZBJTBCTSBSDHRTJJBYTCXYJEYLXCBNEBJDSYXYKGSJZBXBYTFZWGENYHHTHZHHXFWGCSTBGXKLSXYWMTMBYXJSTZSCDYQRCYTWXZFHMYMCXLZNSDJTTTXRYCFYJSBSDYERXJLJXBBDEYNJGHXGCKGSCYMBLXJMSZNSKGXFBNBPTHFJAAFXYXFPXMYPQDTZCXZZPXRSYWZDLYBBKTYQPQJPZYPZJZNJPZJLZZFYSBTTSLMPTZRTDXQSJEHBZYLZDHLJSQMLHTXTJECXSLZZSPKTLZKQQYFSYGYWPCPQFHQHYTQXZKRSGTTSQCZLPTXCDYYZXSQZSLXLZMYCPCQBZYXHBSXLZDLTCDXTYLZJYYZPZYZLTXJSJXHLPMYTXCQRBLZSSFJZZTNJYTXMYJHLHPPLCYXQJQQKZZSCPZKSWALQSBLCCZJSXGWWWYGYKTJBBZTDKHXHKGTGPBKQYSLPXPJCKBMLLXDZSTBKLGGQKQLSBKKTFXRMDKBFTPZFRTBBRFERQGXYJPZSSTLBZTPSZQZSJDHLJQLZBPMSMMSXLQQNHKNBLRDDNXXDHDDJCYYGYLXGZLXSYGMQQGKHBPMXYXLYTQWLWGCPBMQXCYZYDRJBHTDJYHQSHTMJSBYPLWHLZFFNYPMHXXHPLTBQPFBJWQDBYGPNZTPFZJGSDDTQSHZEAWZZYLLTYYBWJKXXGHLFKXDJTMSZSQYNZGGSWQSPHTLSSKMCLZXYSZQZXNCJDQGZDLFNYKLJCJLLZLMZZNHYDSSHTHZZLZZBBHQZWWYCRZHLYQQJBEYFXXXWHSRXWQHWPSLMSSKZTTYGYQQWRSLALHMJTQJSMXQBJJZJXZYZKXBYQXBJXSHZTSFJLXMXZXFGHKZSZGGYLCLSARJYHSLLLMZXELGLXYDJYTLFBHBPNLYZFBBHPTGJKWETZHKJJXZXXGLLJLSTGSHJJYQLQZFKCGNNDJSSZFDBCTWWSEQFHQJBSAQTGYPQLBXBMMYWXGSLZHGLZGQYFLZBYFZJFRYSFMBYZHQGFWZSYFYJJPHZBYYZFFWODGRLMFTWLBZGYCQXCDJYGZYYYYTYTYDWEGAZYHXJLZYYHLRMGRXXZCLHNELJJTJTPWJYBJJBXJJTJTEEKHWSLJPLPSFYZPQQBDLQJJTYYQLYZKDKSQJYYQZLDQTGJQYZJSUCMRYQTHTEJMFCTYHYPKMHYZWJDQFHYYXWSHCTXRLJHQXHCCYYYJLTKTTYTMXGTCJTZAYYOCZLYLBSZYWJYTSJYHBYSHFJLYGJXXTMZYYLTXXYPZLXYJZYZYYPNHMYMDYYLBLHLSYYQQLLNJJYMSOYQBZGDLYXYLCQYXTSZEGXHZGLHWBLJHEYXTWQMAKBPQCGYSHHEGQCMWYYWLJYJHYYZLLJJYLHZYHMGSLJLJXCJJYCLYCJPCPZJZJMMYLCQLNQLJQJSXYJMLSZLJQLYCMMHCFMMFPQQMFYLQMCFFQMMMMHMZNFHHJGTTHHKHSLNCHHYQDXTMMQDCYZYXYQMYQYLTDCYYYZAZZCYMZYDLZFFFMMYCQZWZZMABTBYZTDMNZZGGDFTYPCGQYTTSSFFWFDTZQSSYSTWXJHXYTSXXYLBYQHWWKXHZXWZNNZZJZJJQJCCCHYYXBZXZCYZTLLCQXYNJYCYYCYNZZQYYYEWYCZDCJYCCHYJLBTZYYCQWMPWPYMLGKDLDLGKQQBGYCHJXY", t = n.charCodeAt(0);
        return t > 40869 || t < 19968 ? n : i[t] ? i[t] : r.charAt(t - 19968)
    }

    function u(n) {
        for (var i = [""], f, o, t, s, u, r, e = 0, h = n.length; e < h; e++)if (f = n[e], o = f.length, o == 1)for (t = 0; t < i.length; t++)i[t] += f; else for (s = i.slice(0), i = [], t = 0; t < o; t++) {
            for (u = s.slice(0), r = 0; r < u.length; r++)u[r] += f.charAt(t);
            i = i.concat(u)
        }
        return i
    }

    for (var r = [], i, n = 0, t = this.length; n < t; n++)i = this.charAt(n), r.push(f(i));
    return u(r)
}, String.prototype.checkStrongAsPwd = function () {
    function r(n) {
        return n >= 48 && n <= 57 ? 1 : n >= 65 && n <= 90 ? 2 : n >= 97 && n <= 122 ? 4 : 8
    }

    function t(n) {
        for (modes = 0, i = 0; i < 4; i++)n & 1 && modes++, n >>>= 1;
        return modes
    }

    function n(n) {
        if (n.length <= 4)return 0;
        for (Modes = 0, i = 0; i < n.length; i++)Modes |= r(n.charCodeAt(i));
        return t(Modes)
    }

    return n(this)
}, String.prototype.pad = function (n) {
    for (var t = this, i = this.length; i < n;)t = "0" + t, i++;
    return t
}, function (n) {
    n.extend({
        setCookie: function () {
            function i(n, t, i) {
                var r = new Date;
                r.setDate(r.getDate() + i), document.cookie = n + "=" + escape(t) + (i == null ? "" : ";expires=" + r.toUTCString())
            }

            var n = arguments[0], t, r;
            if (typeof n != undefined)if (typeof n == "object" && this.isArray(n))for (t = 0, r = n.length; t < r; t++)i(n[t].name, n[t].value, n[t].expiredays); else i(arguments[0], arguments[1], arguments[2])
        }, getCookie: function (n) {
            var u, f, r, t, e, i;
            if (document.cookie.length > 0 && n)if (f = document.cookie, f.indexOf(n) == -1)u = undefined; else for (r = f.split("; "), t = 0, e = r.length; t < e; t++)i = r[t].split("="), i[0] == n && (u = i[1]);
            return u
        }, removeCookie: function (n) {
            this.setCookie(n, "", -1)
        }
    })
}(jQuery), function (n) {
    n.extend(n.fn, {
        getCss: function (n) {
            var t = parseInt(this.css(n));
            return isNaN(t) ? !1 : t
        }
    }), n.fn.easydrag = function (t) {
        var i = n.extend({
            zIndex: 20, opacity: 1, handler: null, onMove: function () {
            }, onDrop: function () {
            }
        }, t), r = {
            drag: function (n) {
                var t = n.data.dragData;
                t.target.css({
                    left: t.left + n.pageX - t.offLeft,
                    top: t.top + n.pageY - t.offTop
                }), t.handler.css({cursor: "move"});
                t.onMove(n)
            }, drop: function (t) {
                var i = t.data.dragData;
                i.target.css(i.oldCss), i.handler.css("cursor", i.oldCss.cursor);
                i.onDrop(t);
                n(document).unbind("mousemove", r.drag).unbind("mouseup", r.drop)
            }
        };
        return this.each(function () {
            var u = this, t = null;
            t = typeof i.handler == "undefined" || i.handler == null ? n(u) : typeof i.handler == "string" ? n(i.handler, this) : i.handle, t.bind("mousedown", {e: u}, function (u) {
                var f = n(u.data.e), e = {}, o;
                if (f.css("position") != "absolute") {
                    try {
                        f.position(e)
                    } catch (s) {
                    }
                    f.css("position", "absolute")
                }
                e.cursor = f.css("cursor") || "default", e.opacity = f.getCss("opacity") || 1, o = {
                    left: n.browser.safari ? e.left || n(f).position().left || 0 : e.left || f.getCss("left") || 0,
                    top: e.top || f.getCss("top") || 0,
                    width: f.width() || f.getCss("width"),
                    height: f.height() || f.getCss("height"),
                    offLeft: u.pageX,
                    offTop: u.pageY,
                    oldCss: e,
                    onMove: i.onMove,
                    onDrop: i.onDrop,
                    handler: t,
                    target: f
                }, f.css("opacity", i.opacity), n(this).css({cursor: "move"}), n(document).bind("mousemove", {dragData: o}, r.drag).bind("mouseup", {dragData: o}, r.drop)
            })
        })
    }
}(jQuery), function (n) {
    n.message = function (t) {
        function f() {
            function l() {
                var i = parseInt(n("label em", t).html());
                i == 1 && u(), n("label em", t).html(i - 1)
            }

            var s, o, t, e;
            if (r.data("message") && u(!0), r.data("lastFocusElem", n(":focus")), !n.browser.msie && n(":focus").trigger("blur"), i.bind && i.bind.length > 0)for (e = 0; o = i.bind[e++];)n(o[0]).off(o[1]), n(o[0]).die(o[1], o[2]);
            n('<div class="mask" id="mask"></div>').css({height: document.documentElement.scrollHeight}).appendTo(r), t = n('<div class="si-message-box" id="si-message-box"></div>'), n('<div class="message-title"><h3>' + i.title[i.type] + '</h3><a title="关闭(Esc)"></a></div>').appendTo(t);
            var f = n('<div class="message-main"><div class="user-message"><b class="{0}"></b><p>{1}</p></div></div>'.format(i.type, i.msg)), v = n('<p class="surplus"><input type="checkbox" checked="checked" id="confirmClose"><label for="confirmClose"><em>{0}</em>秒后自动关闭</label></p>'.format(i.timeout / 1e3)).appendTo(f), a = n('<a href="#" class="si-button confirm blue current mr-15">确定</a>').appendTo(f), h = n('<a href="#" class="si-button cancel mr-15" style="display:none;">取消</a>').appendTo(f), c = n('<a href="#" class="si-button close" style="display:none;">取消</a>').appendTo(f);
            if (t.append(f), t.appendTo(r), t.css({
                    left: (n(window).width() - t.width()) / 2 + n(document).scrollLeft() + "px",
                    top: (n(window).height() - t.height()) / 2 + n(document).scrollTop() + "px"
                }), i.width && t.css("width", i.width), i.buttons && i.buttons.length)for (e = 0; e < i.buttons.length; e++)n('<a href="{1}" class="si-button" >{0}</a>'.format(i.buttons[e].text, i.buttons[e].url)).appendTo(n(".message-main", t));
            i.timeout == 0 && n("p.surplus", t).hide(), typeof i.title == "string" && n(".message-title h3", t).html(i.title), /confirm/.test(i.type) && (h.show(), n("p.surplus", t).hide(), i.type === "confirms" && (a.html("保存"), h.html("不保存"), c.show())), i.type === "normal" && n("#mask").hide();
            n(".si-button", f).off("click").on("click", function () {
                if (n(this).attr("href") == "#")return !1;
                var t = this;
                return n.ajax({
                    type: "get", url: n(t).attr("href"), success: function (t) {
                        t.status && n.message({msg: t.message.msg, callback: i.callback})
                    }
                }), !1
            });
            n(".message-title a", t).add(c).on("click", function () {
                return u(), !1
            });
            a.add(h).on("click", function () {
                if (u(), /confirm/.test(i.type)) {
                    var t = n(this).attr("class").indexOf("confirm") == -1 ? !1 : !0;
                    i.fn(t)
                }
                return !1
            });
            t.easydrag({handler: ".message-title"});
            n(document.body).on("keydown.message", function (t) {
                var i = n("a:visible", f).index(n("a.current", f));
                switch (t.which) {
                    case 13:
                        return n("a.current", f).trigger("click"), !1;
                    case 37:
                        i > 0 && (n("a", f).removeClass("current"), n("a:visible", f).eq(i - 1).addClass("current"));
                        break;
                    case 39:
                        i < n("a:visible", f).length - 1 && (n("a", f).removeClass("current"), n("a:visible", f).eq(i + 1).addClass("current"));
                        break;
                    case 27:
                        return u(), !1
                }
                t.stopPropagation()
            });
            /confirm/.test(i.type) || (s = setInterval(l, 1e3), r.data("gTimer", s));
            n(':input[type="checkbox"]', t).on("click", function () {
                n(this).attr("checked") !== "checked" && s ? clearInterval(s) : s = setInterval(l, 1e3)
            });
            r.data("message", this)
        }

        function u(t) {
            var f, u;
            if (r.data("gTimer") && (clearInterval(r.data("gTimer")), r.removeData("gTimer")), n("#si-message-box, #mask").remove(), r.off(".message"), r.data("lastFocusElem") && n(r.data("lastFocusElem")).trigger("focus"), t)return r.removeData("message"), !1;
            if (i.bind && i.bind.length > 0)for (f = 0; f < i.bind.length; f++)u = i.bind[f], !!u[0] && !!u[2] && n(u[0]).off(u[1]).on(u[1], u[2]);
            i.callback && i.callback.call(this), r.removeData("message")
        }

        var e = this, r = n(document.body), i = typeof t == "string" ? n.extend({}, n.message.defaults, {msg: t}) : n.extend({}, n.message.defaults, t);
        return i.type == "normal" && (i.timeout = 3e3), i.type == "isNotExist" && (i.type = "confirm"), f()
    }, n.message.defaults = {
        msg: "这是一个消息框.",
        type: "info",
        title: {
            info: "提示",
            normal: "提示",
            succeed: "成功",
            confirm: "系统提示",
            confirms: "系统提示",
            error: "错误",
            warning: "警告",
            loginTimeout: "登录超时",
            unAuthorized: "无权限",
            isNotExist: "不存在"
        },
        fn: new Function,
        timeout: 5e3,
        bind: [],
        buttons: [],
        callback: function () {
        }
    }
}(jQuery), function (n) {
    n.fn.validate = function (t) {
        var i = n.data(this[0], "validator");
        return i || (i = new n.validator(this[0], t), n.data(this[0], "validator", i)), i.form() ? !0 : (i.focusInvalid(), !1)
    }, n.fn.validateDelegate = function (t, i, r) {
        return this.on(i, function (i) {
            var u = n(i.target);
            if (u.is(t))return r.apply(u, arguments)
        })
    }, n.fn.validateErrors = function (t, i) {
        var u = this, r = n.data(this[0], "validator");
        setTimeout(function () {
            for (var e, f, o = 0; o < t.length; o++)if (e = t[o], f = e.element[0], e.rule)r || (r = new n.validator(u[0]), n.data(u[0], "validator", r)), n(f).attr(r.settings.attrPrefix + "-regex-pattern", e.rule), n(f).attr(r.settings.attrPrefix + "-regex", e.msg); else {
                if (r || (r = new n.validator(u[0], !1), e.validateTipType && (r.settings.tipType = e.validateTipType), n.data(u[0], "validator", r)), i === !1) {
                    r.settings.unhighlight && r.settings.unhighlight.call(u, r.settings.wrapper ? f.parentNode : f, r.settings.errorClass, r.settings.validClass), r.removeTip(f);
                    return
                }
                r.settings.highlight && r.settings.highlight.call(u, r.settings.wrapper ? f.parentNode : n(f), r.settings.errorClass, r.settings.validClass), f.focus(), r.addTip(f, e.msg)
            }
        }, 50)
    }, n.validator = function (t, i) {
        (this.settings = n.extend(!0, {}, n.validator.defaults, i), this.currentForm = t, i !== !1) && this.init()
    }, n.validator.format = function (t, i) {
        return arguments.length == 1 ? function () {
            var i = n.makeArray(arguments);
            return i.unshift(t), n.validator.format.apply(this, i)
        } : (arguments.length > 2 && i.constructor != Array && (i = n.makeArray(arguments).slice(1)), i.constructor != Array && (i = [i]), n.each(i, function (n, i) {
            t = t.replace(new RegExp("\\{" + n + "\\}", "g"), i)
        }), t)
    }, n.validator.prototype = {
        init: function () {
            function t(t) {
                var i = this[0].form && n.data(this[0].form, "validator") || n.data(this[0], "validator"), r = "on" + t.type.replace(/^validate/, "");
                i && i.settings[r] && i.settings[r].call(i, this[0], t)
            }

            this.reset(), n(this.currentForm).validateDelegate("[type='text'], [type='password'], [type='file'], select, textarea, [type='number'], [type='search'] ,[type='tel'], [type='url'], [type='email'], [type='datetime'], [type='date'], [type='datebox'], [type='month'], [type='week'], [type='time'], [type='datetime-local'], [type='range'], [type='color'] ", "focusin focusout keyup change", t).validateDelegate("[type='radio'], [type='checkbox'], select, option", "click", t), this.settings.invalidHandler && n(this.currentForm).bind("invalid-form.validate", this.settings.invalidHandler)
        }, form: function () {
            var t = this.checkForm();
            return t || n(this.currentForm).triggerHandler("invalid-form", [this]), this.showErrors(), t
        }, checkForm: function () {
            this.reset();
            for (var n = 0, t = this.currentElements = this.elements(); t[n]; n++)this.check(t[n]);
            return this.valid()
        }, reset: function () {
            this.errorList = [], this.errorMap = {}, this.toShow = n([]), this.toHide = n([]), this.currentElements = n([])
        }, elements: function () {
            var t = {};
            return n(this.currentForm).is(this.settings.validateElement) ? n(this.currentForm) : n(this.currentForm).find(this.settings.validateElement).not(this.settings.ignore)
        }, check: function (t) {
            var t = this.validationTargetFor(t), f = this.getRules(t), r, i, u;
            for (r in f) {
                i = {method: r, parameters: f[r]};
                try {
                    if (u = n.validator.methods[r].call(this, t.value.replace(/\r/g, ""), t, i.parameters), !u)return this.formatAndAdd(t, i), !1
                } catch (e) {
                    this.settings.debug && window.console && console.log("exception occured when checking element " + t.id + ", check the '" + i.method + "' method", e);
                    throw e;
                }
            }
            return !0
        }, element: function (t) {
            this.reset(), this.currentElements = n(t);
            var i = this.check(t);
            return this.showErrors(), i
        }, showError: function (t, i, r) {
            r ? (this.settings.unhighlight && this.settings.unhighlight.call(this, this.settings.wrapper ? n(t).parents(this.settings.wrapper).length ? n(t).parents(this.settings.wrapper) : t.parentNode : t, this.settings.errorClass, this.settings.validClass), this.settings.errorShowable && this.removeTip.call(this, t)) : (this.settings.highlight && this.settings.highlight.call(this, this.settings.wrapper ? n(t).parents(this.settings.wrapper).length ? n(t).parents(this.settings.wrapper) : t.parentNode : t, this.settings.errorClass, this.settings.validClass), this.settings.errorShowable && this.addTip.call(this, t, i))
        }, showErrors: function () {
            for (var r, i, t = 0; this.errorList[t]; t++)r = this.errorList[t], this.settings.highlight && this.settings.highlight.call(this, this.settings.wrapper ? n(r.element).parents(this.settings.wrapper).length ? n(r.element).parents(this.settings.wrapper) : r.element.parentNode : n(r.element), this.settings.errorClass, this.settings.validClass), this.settings.errorShowable && this.addTip.call(this, r.element, r.message);
            if (this.settings.unhighlight)for (t = 0, i = this.validElements(); i[t]; t++)this.settings.unhighlight.call(this, this.settings.wrapper ? n(i[t]).parents(this.settings.wrapper).length ? n(i[t]).parents(this.settings.wrapper) : i[t].parentNode : i[t], this.settings.errorClass, this.settings.validClass), this.settings.errorShowable && this.removeTip.call(this, i[t])
        }, validElements: function () {
            return this.currentElements.not(this.invalidElements()).not(":hidden")
        }, invalidElements: function () {
            return n(this.errorList).map(function () {
                return this.element
            })
        }, addTip: function (t, i) {
            var f = n(t), u = n('<div class="validatebox-tip ' + this.settings.errorShowType + ' arrow-left" data-test="1"><span class="tip-header"><b></b></span><span class="tip-content"><span>' + i + "</span></span></div>");
            this.settings.iconShowable && n(".tip-content", u).prepend('<b class="error-icon"></b>'), this.settings.wrapper ? (f = f.parents(this.settings.wrapper), f.children(".validatebox-tip").length ? (f.children(".validatebox-tip").hide(), f.children(".validatebox-tip").find(".tip-content span").html(i), u = f.children(".validatebox-tip"), u.appendTo(f)) : f.parents(".combobox").hasClass("si-g3") ? u.appendTo(f.parents(".combobox").children(this.settings.wrapper).last()) : u.appendTo(f)) : f.next("div").hasClass("validatebox-tip") ? (f.next(".validatebox-tip").hide(), f.next(".validatebox-tip").find(".tip-content span").html(i), u = f.next(".validatebox-tip"), u.insertAfter(f)) : u.insertAfter(f), u.show(), this.settings.tipType === "arrow-down" && (u.removeClass("arrow-left").addClass("arrow-down"), u.css("max-width", this.settings.maxWidth).css("top", -u.height())), this.settings.tipType === "arrow-up" && (u.removeClass("arrow-up").addClass("arrow-up"), u.css("max-width", this.settings.maxWidth).css("top", f.height() + 7)), this.settings.tipType === "arrow-left" && (u.css("max-width", this.settings.maxWidth), u.width() > this.settings.maxWidth ? u.css("right", -(this.settings.maxWidth + 13)) : u.css("right", -(u.width() + 13))), f.focus(function () {
                n(".validatebox-tip", this.currentForm).hide(), u.show()
            }).blur(function () {
                u.hide()
            })
        }, removeTip: function (t) {
            var i = n(t);
            i.next("div").hasClass("validatebox-tip") && i.next("div").remove(), this.settings.wrapper && i.parents(this.settings.wrapper).children(".validatebox-tip").length && i.parents(this.settings.wrapper).children(".validatebox-tip").remove()
        }, idOrName: function (n) {
            return this.checkable(n) ? n.name : n.id || n.name
        }, validationTargetFor: function (n) {
            return this.checkable(n) && (n = this.findByName(n.name).not(this.settings.ignore)[0]), n
        }, checkable: function (n) {
            return /radio|checkbox/i.test(n.type)
        }, findByName: function (t) {
            var i = this.currentForm;
            return n(document.getElementsByTagName("div")).map(function (n, r) {
                return r.form == i && r.getAttribute("name") == t && r || null
            })
        }, getRules: function (t) {
            return n.extend({}, this.attributeRules(t))
        }, attributeRules: function (t) {
            var f = {}, u = n(t), i, r;
            for (i in n.validator.methods)i === "range" || i === "length" ? (r = [], r[0] = u.attr(this.settings.attrPrefix + "-" + i + "-min"), r[1] = u.attr(this.settings.attrPrefix + "-" + i + "-max"), r[0] && r[1] || (r = undefined)) : r = i === "minlength" ? u.attr(this.settings.attrPrefix + "-length-min") : i === "maxlength" ? u.attr(this.settings.attrPrefix + "-length-max") : i === "regex" ? u.attr(this.settings.attrPrefix + "-regex-pattern") : u.attr(this.settings.attrPrefix + "-" + i), r ? f[i] = r : u.attr("type") === i && (f[i] = !0);
            return f
        }, getLength: function (t, i) {
            switch (i.nodeName.toLowerCase()) {
                case"select":
                    return n("option:selected", i).length;
                case"input":
                    if (this.checkable(i))return this.findByName(i.name).filter(":checked").length
            }
            return t.length
        }, valid: function () {
            return this.size() == 0
        }, size: function () {
            return this.errorList.length
        }, focusInvalid: function () {
            var t = this, i;
            if (this.settings.focusInvalid)try {
                i = n(this.errorList.length && this.errorList[0].element || []), n(".form-tab-box .tab-box-item").each(function (r) {
                    if (i.parents(".tab-box-item").is(this)) {
                        n(this).addClass("current").show(), n(this).siblings().removeClass("current").hide(), n(".form-tab-nav ul li").eq(r).addClass("current"), n(".form-tab-nav ul li").eq(r).siblings().removeClass("current"), n(".validatebox-tip", this).each(function () {
                            var i = n(this);
                            t.settings.tipType === "arrow-left" && (i.css("max-width", t.settings.maxWidth), i.width() > t.settings.maxWidth ? i.css("right", -(t.settings.maxWidth + 13)) : i.css("right", -(i.width() + 13)))
                        });
                        return
                    }
                }), i.filter(":visible").focus().trigger("focusin")
            } catch (r) {
            }
        }, metaMessage: function (t, i) {
            return n(t).attr(this.settings.attrPrefix + "-" + i.method)
        }, defaultMessage: function (t, i) {
            return i.method === "regex" || i.method === "required" ? this.metaMessage(t, i) : n.validator.defaults.messages[i.method] || "<strong>Warning: No message defined for method: " + i.method + "</strong>"
        }, formatAndAdd: function (t, i) {
            var r = this.defaultMessage(t, i), u = /\$?\{(\d+)\}/g;
            typeof r == "function" ? r = r.call(this, i.parameters) : u.test(r) && (r = n.validator.format(r.replace(u, "{$1}"), i.parameters)), this.errorList.push({
                message: r,
                element: t
            }), this.errorMap[this.idOrName(t)] = r
        }, formatDate: function (n, t) {
            var u = typeof t == "undefined" ? "si_/" : "si_" + t, i, r;
            if (n = n.replace(/\-/g, u), i = n.split(u), i.length == 1)return n;
            for (i[1] = i[1] === undefined ? "01" : i[1], i[2] = i[2] === undefined ? "01" : i[2], r = 0; r < i.length; r++)parseInt(i[r]) < 10 && (i[r] = "0" + parseInt(i[r]));
            return i.join(u.replace("si_", ""))
        }, newDate: function (n) {
            var r, t, i;
            return (n = n.split(/\s/), !n) ? null : (r = n[0].split(/\/|-/), t = n[1] ? n[1].split(":") : [0, 0, 0], i = new Date, i.setUTCFullYear(r[0], r[1] - 1, r[2]), i.setUTCHours(t[0] - 8, t[1], t[2]), i)
        }
    }, n.validator.methods = {
        required: function (t, i) {
            switch (i.nodeName.toLowerCase()) {
                case"select":
                    var u = n(i).val();
                    return u && u.length > 0;
                case"input":
                    if (this.checkable(i))return this.getLength(t, i) > 0;
                default:
                    return n.trim(t).length > 0
            }
        }, number: function (n) {
            return /^-?(?:\d*|\d{1,3}(?:,\d{3})+)(?:\.\d+)?$/.test(n)
        }, digits: function (n) {
            return /^\d*$/.test(n)
        }, email: function (n) {
            return /(^(((([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*)|((\x22)((((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(([\x01-\x08\x0b\x0c\x0e-\x1f\x7f]|\x21|[\x23-\x5b]|[\x5d-\x7e]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(\\([\x01-\x09\x0b\x0c\x0d-\x7f]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))))*(((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(\x22)))@((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?)?$)/i.test(n)
        }, url: function (n) {
            return /^(https?|ftp):\/\/(((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:)*@)?(((\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5]))|((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?)(:\d*)?)(\/((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)+(\/(([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)*)*)?)?(\?((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|[\uE000-\uF8FF]|\/|\?)*)?(\#((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|\/|\?)*)?$/i.test(n)
        }, date: function (n) {
            return !n || !/Invalid|NaN/.test(this.newDate(n))
        }, dateISO: function (n) {
            return !n || /^\d{4}[\/-]\d{1,2}[\/-]\d{1,2}$/.test(n)
        }, minlength: function (matches, element, param) {
            var param = eval(param);
            return !matches || n.trim(matches).getLength() >= param
        }, maxlength: function (matches, element, param) {
            var param = eval(param);
            return !matches || n.trim(matches).getLength() <= param
        }, length: function (matches, element, param) {
            var len = n.trim(matches).getLength(), params = eval(param);
            return !matches || len >= eval(params[0]) && len <= eval(params[1])
        }, range: function (matches, element, param) {
            var matches = eval(matches.replace(",", "")), params = eval(param);
            return !matches || matches >= eval(params[0]) && matches <= eval(param[1])
        }, creditcard: function (n) {
            return !n || /^(\d{14}|\d{17})(\d|[xX])$/.test(n)
        }, accept: function (n, t, i) {
            return i = typeof i == "string" ? i.replace(/,/g, "|") : "png|jpe?g|gif", !n || !!n.match(new RegExp(".(" + i + ")$", "i")) ? !0 : !1
        }, regex: function (n, t, i) {
            return !n || !!n.match(new RegExp(i, "i"))
        }
    }, n.validator.rules = {
        number: /^-?(?:\d*|\d{1,3}(?:,\d{3})+)(?:\.\d+)?$/,
        email: /(^(((([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*)|((\x22)((((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(([\x01-\x08\x0b\x0c\x0e-\x1f\x7f]|\x21|[\x23-\x5b]|[\x5d-\x7e]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(\\([\x01-\x09\x0b\x0c\x0d-\x7f]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))))*(((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(\x22)))@((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?)?$)/i,
        url: /^(https?|ftp):\/\/(((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:)*@)?(((\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5]))|((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?)(:\d*)?)(\/((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)+(\/(([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)*)*)?)?(\?((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|[\uE000-\uF8FF]|\/|\?)*)?(\#((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|\/|\?)*)?$/i,
        date: /^(?:(?!0000)[0-9]{4}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1[0-9]|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[0-9]{2}(?:0[48]|[2468][048]|[13579][26])|(?:0[48]|[2468][048]|[13579][26])00)-02-29)$/
    }, n.validator.defaults = {
        rules: {},
        errorClass: "validatebox-invalid",
        validClass: "",
        wrapper: ".field-inner",
        focusInvalid: !0,
        validateElement: "input, select, textarea",
        ignore: ":submit, :reset, :image, [disabled], #Id:hidden",
        attrPrefix: "data-val",
        errorShowable: !0,
        errorShowType: "box",
        iconShowable: !1,
        tipType: "arrow-left",
        maxWidth: 600,
        messages: {
            required: "该输入域不可为空.",
            remote: "验证失败,请重新输入.",
            email: "请输入有效的邮箱地址.",
            url: "请输入有效的URL.",
            date: "请输入有效的日期.",
            dateISO: "请输入有效的日期(ISO).",
            number: "请输入有效的数字.",
            digits: "请输入整数.",
            creditcard: "请输入有效的身份证号.",
            equalTo: "请再次输入相同值.",
            accept: "请输入有效的扩展名.",
            maxlength: n.validator.format("字段长度不能超过 {0}."),
            minlength: n.validator.format("字段长度不能少于 {0}."),
            length: n.validator.format("字段最小长度为 {0}, 最大长度为 {1}."),
            range: n.validator.format("输入值必须介于 {0} 和 {1} 之间.")
        },
        onfocusin: function () {
        },
        onfocusout: function () {
        },
        onkeyup: function () {
        },
        onchange: function (n) {
            var i = this;
            window.setTimeout(function () {
                i.element(n)
            }, 50)
        },
        onkeypress: function () {
        },
        onclick: function () {
        },
        highlight: function (t, i, r) {
            t.type === "radio" ? this.findByName(t.name).addClass(i).removeClass(r) : n(t).addClass(i).removeClass(r)
        },
        unhighlight: function (t, i, r) {
            t.type === "radio" ? this.findByName(t.name).removeClass(i).addClass(r) : n(t).removeClass(i).addClass(r)
        }
    }
}(jQuery), function (n) {
    var t = {
        _check: function () {
            return "placeholder"in document.createElement("input")
        }, init: function () {
            this._check() || this.fix()
        }, fix: function () {
            n(":input[placeholder]").each(function () {
                var r = n(this), o = r.attr("placeholder"), e = r.position(), f = r.outerHeight(!0), h = r.outerWidth(), s = r.css("padding-left"), u = n("<span></span>").text(o).css({
                    position: "absolute",
                    overflow: "hidden",
                    "text-align": "left",
                    "text-indent": 2 + parseInt(r.css("text-indent")) + "px",
                    "font-family": "宋体",
                    "font-size": "13px",
                    "letter-spacing": "1px",
                    "word-break": "break-all",
                    left: e.left,
                    top: e.top,
                    height: f,
                    width: h,
                    "line-height": f + "px",
                    "padding-left": s,
                    color: "#A8A8A8"
                });
                r.val() && u.hide(), r.after(u).focusin(function () {
                    u.hide()
                }).focusout(function () {
                    r.val() || u.show()
                }), u.click(function () {
                    u.hide(), r.focus()
                })
            })
        }
    };
    n(function () {
        setTimeout(function () {
            t.init()
        }, 0)
    })
}(jQuery), $(function () {
    function i() {
        var r = !0, i = $("#user_psd").val(), t = $("#user_psd2").val();
        return i && t && (i !== t ? (n.validateErrors([{
            element: $("#user_psd2", n),
            msg: "两次密码请输入一致。"
        }]), r = !1) : n.validateErrors([{element: $("#user_psd2", n)}], !1)), r
    }

    var n = $(".product-login form"), t = $(":text, select, :password", n), r = $("button.login-button", n);
    t.on("mousedown", function () {
    }).on("focus", function () {
        $(this).one("click", function () {
            $(this).addClass("focus").select()
        })
    }).on("blur", function () {
        $(this).removeClass("focus")
    }).on("keydown", function (i) {
        n = $(this).parents("form"), t = $(":text, select, :password", n), r = $("button.login-button", n);
        switch (i.which) {
            case 13:
                var u = t.index($(this));
                return u === t.length - 1 ? r.trigger("click") : (t.eq(u + 1).focus(), t.eq(u + 1).select()), !1
        }
    });
    $("input[data-val-required], select", ".product-login").parents("td").prev("th").children("label").addClass("required"), $('input[data-val="true"], select', ".product-login").parents("td").addClass("input-td"), $(".field-validation-error", n).length && $(".validation-summary-errors", n).hide();
    r.off("click").on("click", function () {
        n = $(this).parents("form");
        var r = {};
        if ($(this).hasClass("disabled"))return !1;
        if ($(this).parents(".product-login").hasClass("register"))r = {ignore: ":hidden, [disabled]"}, $("table:hidden .validatebox-invalid", n).removeClass("validatebox-invalid"), $("table:hidden .validatebox-tip", n).remove(), $("table:hidden :text", n).val(""), $.when(verifyMobileCode()).done(function () {
            if (!i() || !n.validate(r))return !1;
            n.submit()
        }).fail(function () {
            return !1
        }); else {
            if($("#TenantCode").val()!=null){
                if ($("#TenantCode").val($("#TenantCode").val().replace(/[^0-9]/g, "")), !i() || !n.validate(r))return !1;
            }
            n.submit()
        }
    });
    $(".login .validate-img").on("click", function () {
        this.src = "" + +new Date
    });
    $(".register .validate-img").on("click", function () {
        this.src = "" + +new Date
    });
    $("#user_psd2").off("change").on("change", function () {
        i()
    });
    $("#argeement").on("click", function () {
        var n = $(this).prop("checked") ? !1 : !0;
        $(".login-button", ".register").attr("disabled", n), n ? $(".login-button", ".register").addClass("disabled") : $(".login-button", ".register").removeClass("disabled")
    });
    $(".agreement-wrapper").next("#footer").css("position", "static");
    $(".login ul.login-type li").on("click", function () {
        $(".login ul.login-type li").removeClass("current"), $(this).addClass("current"), $('[name="LoginType"]').val($(this).attr("targ")), $(".login table").hide(), $('.login table[index="{0}"]'.format($(this).attr("targ"))).show(), $(".error-msg").remove()
    });
    $("#LoginType").val() == "1" && ($('.login table[index="0"]').hide(), $('.login table[index="1"]').show(), $('.login ul li[targ="0"]').removeClass("current"), $('.login ul li[targ="1"]').addClass("current"));
    //$("#TenantCode", n).on("keyup", function (n) {
    //    if (n.keyCode == 8 || /37|38|39|40/.test(n.keyCode))return !0;
    //    if ($(this).val().length > 9)return $(this).val($(this).val().substr(0, 9)), !1;
    //    if (/^[0-9]+$/.test($(this).val()) || $(this).val($(this).val().replace(/[^0-9]/g, "")), $(this).val().length > 4) {
    //        var t = $(this).val().split("");
    //        t.splice(4, 0, " "), $(this).val(t.join(""))
    //    }
    //    $(this).val().length == 4 && $(this).val($(this).val() + " ")
    //});
    //$("body").ichat({
    //    placement: "right",
    //    top: 25,
    //    title: "在线客服",
    //    color: "black",
    //    trigger: "hover",
    //    items: [{
    //        type: "qq",
    //        title: "客服QQ",
    //        trigger: "none",
    //        open: !0,
    //        items: [{
    //            title: "技术咨询一",
    //            qq: "",
    //            url: "image/qq_online.gif"
    //        }, {title: "技术咨询二", qq: "", url: "image/qq_online.gif"}]
    //    }, {
    //        type: "tel",
    //        title: "客服电话",
    //        trigger: "none",
    //        open: !0,
    //        items: [{title: "电话", tel: "0532-1292828"}]
    //    }, {
    //        type: "text",
    //        title: "服务时间",
    //        trigger: "none",
    //        open: !0,
    //        items: [{
    //            title: "",
    //            text: "周一至周五：9:00-12:00 <span style='float:right;margin-right:18px'>13:30-18:00</span>"
    //        }]
    //    }]
    //})
}), function (n) {
    n.fn.extend({
        ichat: function (t) {
            var s = "<!-- ichat区域 --><div id='ichatBody' class='ichat-body ichat-display' style=''>  <!-- ichat按钮 -->  <div id='ichatButton' class='ichat-button'>    <b id='ichatButtonName'></b>  </div>  <!-- ichat内容 -->  <div id='ichatContent' class='ichat-content'>  </div></div>", o = "<div>  <div data-ichat-toggle='@id' class='ichat-title'>@title</div>  <div id='@id' class='ichat-list'>  </div></div>", i = {
                util: {
                    ie: function () {
                        for (var n = 3, t = document.createElement("div"), i = t.getElementsByTagName("i"); t.innerHTML = "<!--[if gt IE " + ++n + "]><i></i><![endif]-->", i[0];);
                        return n > 4 ? n : !1
                    }, compatible: function () {
                        var t = i.util.ie();
                        t && (t == 6 || t == 7) && n(window).scroll(function () {
                            var t = parseInt(n(document).scrollTop());
                            n("#ichatBody").css("top", t + 200 + "px")
                        })
                    }
                }, body: {
                    placement: {
                        left: function () {
                            n("#ichatBody").addClass("ichat-pull-left"), n("#ichatButton").addClass("ichat-float-right"), n("#ichatContent").addClass("ichat-float-right")
                        }, right: function () {
                            n("#ichatBody").addClass("ichat-pull-right"), n("#ichatButton").addClass("ichat-float-left"), n("#ichatContent").addClass("ichat-float-left")
                        }
                    }, color: {
                        black: function () {
                            n("#ichatButton").addClass("ichat-color-black")
                        }, blue: function () {
                            n("#ichatButton").addClass("ichat-color-blue")
                        }, red: function () {
                            n("#ichatButton").addClass("ichat-color-red")
                        }, green: function () {
                            n("#ichatButton").addClass("ichat-color-green")
                        }, purple: function () {
                            n("#ichatButton").addClass("ichat-color-purple")
                        }
                    }, trigger: {
                        click: function () {
                            n("#ichatButton").click(function () {
                                n("#ichatContent").toggle("slow")
                            })
                        }, hover: function () {
                            var t;
                            n("#ichatBody").hover(function () {
                                clearTimeout(t), t = setTimeout(function () {
                                    n("#ichatContent").show("slow", function () {
                                        clearTimeout(t)
                                    })
                                }, 300)
                            }, function () {
                                clearTimeout(t), n("#ichatContent").hide("slow", function () {
                                    clearTimeout(t)
                                })
                            })
                        }
                    }
                }, items: {
                    qq: function (t) {
                        for (var f = "http://wpa.qq.com/msgrd?v=3&uin=@qq&site=qq&menu=yes", e = "background-image: url('@url');", r = "<ul class='ichat-list-ul'>", i, u = 0; u < t.items.length; u++)i = t.items[u], r += i.image ? "<li><a href='" + f.replace("@qq", i.qq) + "' style=\"" + e.replace("@url", i.image) + "\" target='_blank'>" + i.title + "</a></li>" : i.url ? "<li><a href='" + f.replace("@qq", i.qq) + "' target='_blank'><img border=0 src='" + i.url + "' alt='点击这里给我发消息' />" + i.title + "</a></li>" : "<li><a href='" + f.replace("@qq", i.qq) + "' class='ichat-qq' target='_blank'>" + i.title + "</a></li>";
                        r += "</ul>", n("#" + t.id).html(r)
                    }, tel: function (t) {
                        for (var f = "background-image: url('@url');", r = "<ul class='ichat-list-ul'>", i, u = 0; u < t.items.length; u++)i = t.items[u], r += i.image ? "<li><a href='javascript:void(0);' title='" + i.title + "' style=\"" + f.replace("@url", i.image) + '">' + i.tel + "</a></li>" : "<li><a href='javascript:void(0);' title='" + i.title + "' class='ichat-tel'>" + i.tel + "</a></li>";
                        r += "</ul>", n("#" + t.id).html(r)
                    }, text: function (t) {
                        for (var u = "", i, r = 0; r < t.items.length; r++)i = t.items[r], u += i.href ? "<p><b>" + i.title + "</b><a href='" + i.href + "' target='_blank'>" + i.text + "</a></p>" : "<p><b>" + i.title + "</b>" + i.text + "</p>";
                        n("#" + t.id).html(u)
                    }, trigger: {
                        click: function (t) {
                            n("div[data-ichat-toggle='" + t + "']").addClass("ichat-cursor"), n("div[data-ichat-toggle='" + t + "']").click(function () {
                                n("#" + t).slideToggle("slow")
                            })
                        }, hover: function (t) {
                            var i;
                            n("div[data-ichat-toggle='" + t + "']").addClass("ichat-cursor"), n("div[data-ichat-toggle='" + t + "']").parent().hover(function () {
                                i = setTimeout(function () {
                                    n("#" + t).show("slow")
                                }, 200)
                            }, function () {
                                clearTimeout(i), n("#" + t).hide("slow")
                            })
                        }, none: function () {
                        }
                    }
                }
            }, u;
            for (n(this).append(s), n("#ichatBody").attr("style", "top:" + t.top + "%;"), n("#ichatButtonName").text(t.title), i.body.placement[t.placement] && i.body.placement[t.placement](), i.body.color[t.color] && i.body.color[t.color](), i.body.trigger[t.trigger] && i.body.trigger[t.trigger](), u = 0; u < t.items.length; u++) {
                var r = t.items[u], f = "ichatItem" + u, e = o.replace(/@id/g, f);
                e = e.replace("@title", r.title), n("#ichatContent").append(e), r.open || n("#" + f).addClass("ichat-display"), r.id = f, i.items[r.type] && i.items[r.type](r), i.items.trigger[r.trigger] && i.items.trigger[r.trigger](f)
            }
            i.util.compatible(), n("#ichatBody").removeClass("ichat-display")
        }
    })
}(jQuery)